// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as OptionService$Wonderjs from "../../../../atom/OptionService.js";

function getRecord(param) {
  return OptionService$Wonderjs.unsafeGet(param[/* basicSourceTextureRecord */13]);
}

export {
  getRecord ,
  
}
/* OptionService-Wonderjs Not a pure module */
