export enum EBlendFunc{
    ZERO = "ZEOR",
    ONE = "ONE",
    SRC_COLOR = "SRC_COLOR",
    ONE_MINUS_SRC_COLOR = "ONE_MINUS_SRC_COLOR",
    DST_COLOR = "DST_COLOR",
    ONE_MINUS_DST_COLOR = "ONE_MINUS_DST_COLOR",
    SRC_ALPHA = "SRC_ALPHA",
    SRC_ALPHA_SATURATE = "SRC_ALPHA_SATURATE",
    ONE_MINUS_SRC_ALPHA = "ONE_MINUS_SRC_ALPHA",
    DST_ALPHA = "DST_ALPHA",
    ONE_MINUS_DST_ALPH = "ONE_MINUS_DST_ALPHA"
}
