export enum ETextureFilterMode{
    NEAREST = "NEAREST",
    NEAREST_MIPMAP_MEAREST = "NEAREST_MIPMAP_MEAREST",
    NEAREST_MIPMAP_LINEAR = "NEAREST_MIPMAP_LINEAR",
    LINEAR = "LINEAR",
    LINEAR_MIPMAP_NEAREST = "LINEAR_MIPMAP_NEAREST",
    LINEAR_MIPMAP_LINEAR = "LINEAR_MIPMAP_LINEAR"
}

