// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function getGpuDetectData(state) {
  return state[/* gpuDetectData */6];
}

export {
  getGpuDetectData ,
  
}
/* No side effect */
