// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function setRoot(_, _$1, _$2) {
  window.innerWidth = 100;
  window.innerHeight = 200;
  return /* tuple */[
          100,
          200
        ];
}

exports.setRoot = setRoot;
/* No side effect */
