// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as RecordBasicSourceTextureMainService$Wonderjs           from "./basic_source/RecordBasicSourceTextureMainService.js";
import * as RecordArrayBufferViewSourceTextureMainService$Wonderjs from "./arrayBufferView_source/RecordArrayBufferViewSourceTextureMainService.js";

function setFlipY(gl, flipY, _) {
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, flipY);
  return /* () */0;
}

function clearNeedAddedSourceArr(state) {
  var newrecord = state.slice();
  var newrecord$1 = RecordBasicSourceTextureMainService$Wonderjs.getRecord(state).slice();
  newrecord[/* basicSourceTextureRecord */18] = /* Some */[(newrecord$1[/* needAddedSourceArray */12] = /* array */[], newrecord$1)];
  var newrecord$2 = RecordArrayBufferViewSourceTextureMainService$Wonderjs.getRecord(state).slice();
  newrecord[/* arrayBufferViewSourceTextureRecord */19] = /* Some */[(newrecord$2[/* needAddedSourceArray */14] = /* array */[], newrecord$2)];
  return newrecord;
}

export {
  setFlipY                ,
  clearNeedAddedSourceArr ,
  
}
/* RecordBasicSourceTextureMainService-Wonderjs Not a pure module */
