// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as OptionService$Wonderjs from "../../../../atom/OptionService.js";

function getPositionMap(record) {
  return OptionService$Wonderjs.unsafeGet(record[/* positionMap */1]);
}

export {
  getPositionMap ,
  
}
/* OptionService-Wonderjs Not a pure module */
