// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as GameObject$Wonderjs           from "../../../../../src/ecs/admin/api/GameObject.js";
import * as InstanceTool$Wonderjs         from "../../component/instance/InstanceTool.js";
import * as RenderJobsTool$Wonderjs       from "../core/render/jobs/RenderJobsTool.js";
import * as SourceInstance$Wonderjs       from "../../../../../src/ecs/component/api/instance/SourceInstance.js";
import * as WebGLRenderTool$Wonderjs      from "../core/WebGLRenderTool.js";
import * as CameraControllerTool$Wonderjs from "../../component/cameraController/CameraControllerTool.js";

function createSourceInstanceGameObject(sandbox, state) {
  var match = RenderJobsTool$Wonderjs.prepareGameObject(sandbox, state);
  var gameObject = match[1];
  var match$1 = SourceInstance$Wonderjs.createSourceInstance(match[0]);
  var sourceInstance = match$1[1];
  var match$2 = SourceInstance$Wonderjs.createSourceInstanceObjectInstance(sourceInstance, match$1[0]);
  var state$1 = GameObject$Wonderjs.addGameObjectSourceInstanceComponent(gameObject, sourceInstance, match$2[0]);
  return /* tuple */[
          state$1,
          gameObject,
          /* tuple */[
            match[2],
            match[3],
            match[4],
            sourceInstance,
            match$2[1]
          ]
        ];
}

function prepare(sandbox, state) {
  var state$1 = InstanceTool$Wonderjs.setGpuDetectDataAllowHardwareInstance(sandbox, state);
  var match = createSourceInstanceGameObject(sandbox, state$1);
  var match$1 = CameraControllerTool$Wonderjs.createCameraGameObject(match[0]);
  return /* tuple */[
          match$1[0],
          match[1],
          match[2]
        ];
}

var render = WebGLRenderTool$Wonderjs.render;

export {
  createSourceInstanceGameObject ,
  prepare                        ,
  render                         ,
  
}
/* GameObject-Wonderjs Not a pure module */
