// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as BufferDirectionLightService$Wonderjs from "../../../main/light/direction/BufferDirectionLightService.js";

function createTypeArrays(buffer, _) {
  return /* tuple */[
          new Float32Array(buffer, BufferDirectionLightService$Wonderjs.getColorsOffset(/* () */0), BufferDirectionLightService$Wonderjs.getColorsLength(/* () */0)),
          new Float32Array(buffer, BufferDirectionLightService$Wonderjs.getIntensitiesOffset(/* () */0), BufferDirectionLightService$Wonderjs.getIntensitiesLength(/* () */0))
        ];
}

export {
  createTypeArrays ,
  
}
/* BufferDirectionLightService-Wonderjs Not a pure module */
