// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as GPUDetectService$Wonderjs     from "../../../service/record/all/gpu/GPUDetectService.js";
import * as DeviceManagerService$Wonderjs from "../../../service/record/all/device/DeviceManagerService.js";

function execJob(_, state) {
  var newrecord = state.slice();
  newrecord[/* gpuDetectRecord */5] = GPUDetectService$Wonderjs.detect(DeviceManagerService$Wonderjs.unsafeGetGl(state[/* deviceManagerRecord */9]), state[/* gpuDetectRecord */5]);
  return newrecord;
}

export {
  execJob ,
  
}
/* GPUDetectService-Wonderjs Not a pure module */
