// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ArrayService$Wonderjs                                  from "../../../service/atom/ArrayService.js";
import * as InitTextureService$Wonderjs                            from "../../../service/primitive/texture/InitTextureService.js";
import * as DeviceManagerService$Wonderjs                          from "../../../service/record/all/device/DeviceManagerService.js";
import * as RecordBasicSourceTextureMainService$Wonderjs           from "../../../service/state/main/texture/basic_source/RecordBasicSourceTextureMainService.js";
import * as RecordArrayBufferViewSourceTextureMainService$Wonderjs from "../../../service/state/main/texture/arrayBufferView_source/RecordArrayBufferViewSourceTextureMainService.js";

function execJob(_, state) {
  var basicSourceTextureRecord = RecordBasicSourceTextureMainService$Wonderjs.getRecord(state);
  var arrayBufferViewSourceTextureRecord = RecordArrayBufferViewSourceTextureMainService$Wonderjs.getRecord(state);
  var newrecord = state.slice();
  var newrecord$1 = basicSourceTextureRecord.slice();
  newrecord[/* basicSourceTextureRecord */18] = /* Some */[(newrecord$1[/* glTextureMap */9] = InitTextureService$Wonderjs.initTextures(DeviceManagerService$Wonderjs.unsafeGetGl(state[/* deviceManagerRecord */9]), ArrayService$Wonderjs.range(0, basicSourceTextureRecord[/* index */0] - 1 | 0), basicSourceTextureRecord[/* glTextureMap */9]), newrecord$1)];
  var newrecord$2 = arrayBufferViewSourceTextureRecord.slice();
  newrecord[/* arrayBufferViewSourceTextureRecord */19] = /* Some */[(newrecord$2[/* glTextureMap */11] = InitTextureService$Wonderjs.initTextures(DeviceManagerService$Wonderjs.unsafeGetGl(state[/* deviceManagerRecord */9]), ArrayService$Wonderjs.range(0, arrayBufferViewSourceTextureRecord[/* index */0] - 1 | 0), arrayBufferViewSourceTextureRecord[/* glTextureMap */11]), newrecord$2)];
  return newrecord;
}

export {
  execJob ,
  
}
/* ArrayService-Wonderjs Not a pure module */
