// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as TimeControllerService$Wonderjs from "../../../service/record/main/timeController/TimeControllerService.js";

function execJob(_, state) {
  var newrecord = state.slice();
  newrecord[/* timeControllerRecord */30] = TimeControllerService$Wonderjs.start(state[/* timeControllerRecord */30]);
  return newrecord;
}

export {
  execJob ,
  
}
/* TimeControllerService-Wonderjs Not a pure module */
