// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Log$WonderLog                    from "../../../../../../../node_modules/wonder-log/lib/es6_global/src/Log.js";
import * as GLSLSenderSendDataUtils$Wonderjs from "./GLSLSenderSendDataUtils.js";

function getSendNoCachableDataByType(type_) {
  switch (type_) {
    case "mat3" : 
        return GLSLSenderSendDataUtils$Wonderjs.sendMatrix3;
    case "mat4" : 
        return GLSLSenderSendDataUtils$Wonderjs.sendMatrix4;
    default:
      return Log$WonderLog.fatal(Log$WonderLog.buildFatalMessage("getSendNoCachableDataByType", "unknown type:" + (String(type_) + ""), "", "", ""));
  }
}

function getSendCachableDataByType(type_) {
  switch (type_) {
    case "float" : 
        return GLSLSenderSendDataUtils$Wonderjs.sendFloat;
    case "float3" : 
        return GLSLSenderSendDataUtils$Wonderjs.sendFloat3;
    case "vec3" : 
        return GLSLSenderSendDataUtils$Wonderjs.sendVec3;
    default:
      return Log$WonderLog.fatal(Log$WonderLog.buildFatalMessage("getSendCachableDataByType", "unknown type:" + (String(type_) + ""), "", "", ""));
  }
}

export {
  getSendNoCachableDataByType ,
  getSendCachableDataByType   ,
  
}
/* Log-WonderLog Not a pure module */
