// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as Most from "most";
import * as Curry from "../../../../node_modules/bs-platform/lib/es6/curry.js";

function createFetchJsonStream(filePath, fetchFunc) {
  return Most.fromPromise(Curry._1(fetchFunc, filePath).then((function (prim) {
                    return prim.json();
                  })));
}

function createFetchArrayBufferStream(filePath, fetchFunc) {
  return Most.fromPromise(Curry._1(fetchFunc, filePath).then((function (prim) {
                    return prim.arrayBuffer();
                  })));
}

export {
  createFetchJsonStream ,
  createFetchArrayBufferStream ,
  
}
/* most Not a pure module */
