// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Sinon                             from "../../../../../../../../../node_modules/wonder-bs-sinon/lib/es6_global/src/sinon.js";
import * as TestTool$Wonderjs                 from "../../../../TestTool.js";
import * as FakeGlTool$Wonderjs               from "../../../../gl/FakeGlTool.js";
import * as GeometryTool$Wonderjs             from "../../../../component/geometry/GeometryTool.js";
import * as RenderConfigTool$Wonderjs         from "../../../config/RenderConfigTool.js";
import * as WebGLRenderAdmin$Wonderjs         from "../../../../../../../src/renderer/core/admin/WebGLRenderAdmin.js";
import * as InitBasicMaterialJobTool$Wonderjs from "../jobs/InitBasicMaterialJobTool.js";

function initWithRenderConfig(sandbox) {
  return TestTool$Wonderjs.initWithRenderConfig(sandbox, /* None */0, /* Some */[GeometryTool$Wonderjs.buildBufferConfig(1000)], RenderConfigTool$Wonderjs.buildRenderConfig(/* Some */["\n    {\n    \"platform\": \"pc\",\n    \"browser\": [\n        {\n            \"name\": \"chrome\",\n            \"version\": \"newest\"\n        },\n        {\n            \"name\": \"firefox\",\n            \"version\": \"newest\"\n        }\n    ],\n    \"backend\": {\n        \"name\": \"webgl1\"\n    },\n    \"init_pipeline\": \"simple_basic_render\",\n    \"render_pipeline\": \"simple_basic_render\"\n}\n"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0), /* () */0);
}

function prepareForJudgeGLSL(sandbox, state) {
  var match = InitBasicMaterialJobTool$Wonderjs.prepareGameObject(sandbox, state);
  var shaderSource = Sinon.createEmptyStubWithJsObjSandbox(sandbox);
  var createProgram = Sinon.createEmptyStubWithJsObjSandbox(sandbox);
  var state$1 = FakeGlTool$Wonderjs.setFakeGl(FakeGlTool$Wonderjs.buildFakeGl(sandbox, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[shaderSource], /* Some */[createProgram], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0), match[0]);
  WebGLRenderAdmin$Wonderjs.init(GeometryTool$Wonderjs.initGeometrys(state$1));
  return shaderSource;
}

export {
  initWithRenderConfig ,
  prepareForJudgeGLSL  ,
  
}
/* Sinon Not a pure module */
