module wd{
    export enum EVariableSemantic{
        VERTICE = <any>"VERTICE",
        INDICE = <any>"INDICE",
        NORMAL = <any>"NORMAL",
        TEXCOORD = <any>"TEXCOORD",
        TANGENT = <any>"TANGENT",
        COLOR = <any>"COLOR",

        MODEL_VIEW_PROJECTION = <any>"MODEL_VIEW_PROJECTION"

        //"LOCAL" (FLOAT_MAT4), "MODEL" (FLOAT_MAT4), "VIEW" (FLOAT_MAT4), "PROJECTION" (FLOAT_MAT4), "MODELVIEW" (FLOAT_MAT4), "MODELVIEWPROJECTION" (FLOAT_MAT4), "MODELINVERSE" (FLOAT_MAT4), "VIEWINVERSE" (FLOAT_MAT4), "PROJECTIONINVERSE" (FLOAT_MAT4), "MODELVIEWINVERSE" (FLOAT_MAT4), "MODELVIEWPROJECTIONINVERSE" (FLOAT_MAT4), "MODELINVERSETRANSPOSE" (FLOAT_MAT3), "MODELVIEWINVERSETRANSPOSE" (FLOAT_MAT3), "VIEWPORT" (FLOAT_VEC4).
}
}

