// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ArrayService$WonderCommonlib         from "../../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/ArrayService.js";
import * as IndexComponentService$Wonderjs       from "../../../primitiive/component/IndexComponentService.js";
import * as SparseMapService$WonderCommonlib     from "../../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/SparseMapService.js";
import * as StaticSourceInstanceService$Wonderjs from "./StaticSourceInstanceService.js";

function create(record) {
  var objectInstanceArrayMap = record[/* objectInstanceArrayMap */1];
  var match = IndexComponentService$Wonderjs.generateIndex(record[/* index */0], record[/* disposedIndexArray */6]);
  var index = match[0];
  SparseMapService$WonderCommonlib.set(index, ArrayService$WonderCommonlib.createEmpty(/* () */0), objectInstanceArrayMap);
  var record$1 = StaticSourceInstanceService$Wonderjs.markIsSendTransformMatrixData(index, /* false */0, StaticSourceInstanceService$Wonderjs.markModelMatrixIsStatic(index, /* true */1, record));
  return /* tuple */[
          /* record */[
            /* index */match[1],
            /* objectInstanceArrayMap */objectInstanceArrayMap,
            /* matrixInstanceBufferCapacityMap */record$1[/* matrixInstanceBufferCapacityMap */2],
            /* matrixFloat32ArrayMap */record$1[/* matrixFloat32ArrayMap */3],
            /* isTransformStaticMap */record$1[/* isTransformStaticMap */4],
            /* isSendTransformMatrixDataMap */record$1[/* isSendTransformMatrixDataMap */5],
            /* disposedIndexArray */match[2],
            /* gameObjectMap */record$1[/* gameObjectMap */7]
          ],
          index
        ];
}

export {
  create ,
  
}
/* ArrayService-WonderCommonlib Not a pure module */
