// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as SparseMapService$Wonderjs        from "../../../atom/SparseMapService.js";
import * as ArrayService$WonderCommonlib     from "../../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/ArrayService.js";
import * as CopyTypeArrayService$Wonderjs    from "../../../primitiive/CopyTypeArrayService.js";
import * as SparseMapService$WonderCommonlib from "../../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/SparseMapService.js";

function create() {
  return /* record */[
          /* index */0,
          /* objectInstanceArrayMap */SparseMapService$WonderCommonlib.createEmpty(/* () */0),
          /* matrixInstanceBufferCapacityMap */SparseMapService$WonderCommonlib.createEmpty(/* () */0),
          /* matrixFloat32ArrayMap */SparseMapService$WonderCommonlib.createEmpty(/* () */0),
          /* isTransformStaticMap */SparseMapService$WonderCommonlib.createEmpty(/* () */0),
          /* isSendTransformMatrixDataMap */SparseMapService$WonderCommonlib.createEmpty(/* () */0),
          /* disposedIndexArray */ArrayService$WonderCommonlib.createEmpty(/* () */0),
          /* gameObjectMap */SparseMapService$WonderCommonlib.createEmpty(/* () */0)
        ];
}

function deepCopyForRestore(param) {
  return /* record */[
          /* index */param[/* index */0],
          /* objectInstanceArrayMap */CopyTypeArrayService$Wonderjs.deepCopyArrayArray(param[/* objectInstanceArrayMap */1]),
          /* matrixInstanceBufferCapacityMap */SparseMapService$Wonderjs.copy(param[/* matrixInstanceBufferCapacityMap */2]),
          /* matrixFloat32ArrayMap */CopyTypeArrayService$Wonderjs.deepCopyFloat32ArrayArray(param[/* matrixFloat32ArrayMap */3]),
          /* isTransformStaticMap */SparseMapService$Wonderjs.copy(param[/* isTransformStaticMap */4]),
          /* isSendTransformMatrixDataMap */param[/* isSendTransformMatrixDataMap */5],
          /* disposedIndexArray */param[/* disposedIndexArray */6].slice(),
          /* gameObjectMap */SparseMapService$Wonderjs.copy(param[/* gameObjectMap */7])
        ];
}

export {
  create             ,
  deepCopyForRestore ,
  
}
/* SparseMapService-Wonderjs Not a pure module */
