// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as CopyStateUtils$Wonderjs  from "../../utils/CopyStateUtils.js";
import * as SparseMapSystem$Wonderjs from "../../../../structure/SparseMapSystem.js";

function getCameraControllerData(state) {
  return state[/* cameraControllerData */12];
}

function getPerspectiveCameraDataFromCameraControllerData(cameraControllerData) {
  return cameraControllerData[/* perspectiveCameraData */6];
}

function getPerspectiveCameraData(state) {
  return state[/* cameraControllerData */12][/* perspectiveCameraData */6];
}

function _deepCopyPerspectiveCameraState(perspectiveCameraData) {
  return /* record */[
          /* nearMap */perspectiveCameraData[/* nearMap */0].slice(),
          /* farMap */perspectiveCameraData[/* farMap */1].slice(),
          /* fovyMap */perspectiveCameraData[/* fovyMap */2].slice(),
          /* aspectMap */perspectiveCameraData[/* aspectMap */3].slice()
        ];
}

function deepCopyStateForRestore(state) {
  var match = state[/* cameraControllerData */12];
  var index = match[/* index */0];
  var cameraArray = match[/* cameraArray */1];
  var dirtyArray = match[/* dirtyArray */2];
  var pMatrixMap = match[/* pMatrixMap */3];
  var gameObjectMap = match[/* gameObjectMap */4];
  var updateCameraFuncMap = match[/* updateCameraFuncMap */5];
  var perspectiveCameraData = match[/* perspectiveCameraData */6];
  var disposedIndexArray = match[/* disposedIndexArray */7];
  var newrecord = state.slice();
  newrecord[/* cameraControllerData */12] = /* record */[
    /* index */index,
    /* cameraArray */cameraArray.slice(),
    /* dirtyArray */dirtyArray.slice(),
    /* pMatrixMap */CopyStateUtils$Wonderjs.deepCopyFloat32ArrayArray(pMatrixMap),
    /* gameObjectMap */SparseMapSystem$Wonderjs.copy(gameObjectMap),
    /* updateCameraFuncMap */updateCameraFuncMap.slice(),
    /* perspectiveCameraData */_deepCopyPerspectiveCameraState(perspectiveCameraData),
    /* disposedIndexArray */disposedIndexArray.slice()
  ];
  return newrecord;
}

export {
  getCameraControllerData                          ,
  getPerspectiveCameraDataFromCameraControllerData ,
  getPerspectiveCameraData                         ,
  _deepCopyPerspectiveCameraState                  ,
  deepCopyStateForRestore                          ,
  
}
/* CopyStateUtils-Wonderjs Not a pure module */
