// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ArraySystem$Wonderjs                 from "../../../../structure/ArraySystem.js";
import * as ComponentSystem$Wonderjs             from "../component/ComponentSystem.js";
import * as PerspectiveCameraSystem$Wonderjs     from "./PerspectiveCameraSystem.js";
import * as CameraControllerDirtyCommon$Wonderjs from "./CameraControllerDirtyCommon.js";
import * as CameraControllerStateCommon$Wonderjs from "./CameraControllerStateCommon.js";

function create(state) {
  var data = CameraControllerStateCommon$Wonderjs.getCameraControllerData(state);
  var match = ComponentSystem$Wonderjs.generateIndex(data[/* index */0], data[/* disposedIndexArray */7]);
  var index = match[0];
  var newrecord = state.slice();
  return /* tuple */[
          (newrecord[/* cameraControllerData */14] = /* record */[
              /* index */match[1],
              /* cameraArray */ArraySystem$Wonderjs.push(index, data[/* cameraArray */1]),
              /* dirtyArray */CameraControllerDirtyCommon$Wonderjs.addToDirtyArray(index, data[/* dirtyArray */2]),
              /* pMatrixMap */PerspectiveCameraSystem$Wonderjs.setDefaultPMatrix(index, data[/* pMatrixMap */3]),
              /* gameObjectMap */data[/* gameObjectMap */4],
              /* updateCameraFuncMap */data[/* updateCameraFuncMap */5],
              /* perspectiveCameraData */data[/* perspectiveCameraData */6],
              /* disposedIndexArray */match[2]
            ], newrecord),
          index
        ];
}

export {
  create ,
  
}
/* ArraySystem-Wonderjs Not a pure module */
