// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as CameraControllerStateCommon$Wonderjs     from "./CameraControllerStateCommon.js";
import * as ComponentDisposeComponentCommon$Wonderjs from "../component/ComponentDisposeComponentCommon.js";

function disposeData(cameraController, state) {
  var data = CameraControllerStateCommon$Wonderjs.getPerspectiveCameraData(state);
  ComponentDisposeComponentCommon$Wonderjs.disposeSparseMapData(cameraController, data[/* nearMap */0]);
  ComponentDisposeComponentCommon$Wonderjs.disposeSparseMapData(cameraController, data[/* farMap */1]);
  ComponentDisposeComponentCommon$Wonderjs.disposeSparseMapData(cameraController, data[/* fovyMap */2]);
  ComponentDisposeComponentCommon$Wonderjs.disposeSparseMapData(cameraController, data[/* aspectMap */3]);
  return state;
}

export {
  disposeData ,
  
}
/* CameraControllerStateCommon-Wonderjs Not a pure module */
