let unsafeGetDiffuseColor = LightMaterialOperateCommon.unsafeGetDiffuseColor;

let unsafeGetSpecularColor = LightMaterialOperateCommon.unsafeGetSpecularColor;

let unsafeGetShininess = LightMaterialOperateCommon.unsafeGetShininess;