// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as GlobalTempStateCommon$Wonderjs from "./GlobalTempStateCommon.js";

function getFloat32Array1(state) {
  return GlobalTempStateCommon$Wonderjs.getGlobalTempData(state)[/* float32Array1 */0];
}

var restore = GlobalTempStateCommon$Wonderjs.restore;

export {
  getFloat32Array1 ,
  restore          ,
  
}
/* No side effect */
