// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Caml_array                       from "../../../../../../../node_modules/bs-platform/lib/es6/caml_array.js";
import * as MostUtils$Wonderjs               from "../../../../asset/utils/MostUtils.js";
import * as WorkerService$Wonderjs           from "../../../../service/primitiive/worker/WorkerService.js";
import * as JobConfigService$Wonderjs        from "../../../../service/primitiive/JobConfigService.js";
import * as StateDataMainService$Wonderjs    from "../../../../service/state/main/state/StateDataMainService.js";
import * as WorkerInstanceService$Wonderjs   from "../../../../service/record/workerInstance/WorkerInstanceService.js";
import * as OperateWorkerJobService$Wonderjs from "../../../../service/record/workerJob/OperateWorkerJobService.js";

function execJob(flags, stateData) {
  return MostUtils$Wonderjs.callFunc((function () {
                var state = StateDataMainService$Wonderjs.getState(stateData);
                var operateType = Caml_array.caml_array_get(JobConfigService$Wonderjs.unsafeGetFlags(flags), 0);
                WorkerService$Wonderjs.postMessage({
                      operateType: operateType,
                      pipelineJobs: JSON.stringify(OperateWorkerJobService$Wonderjs.getRenderWorkerPipelineJobs(state[/* workerJobRecord */3])),
                      jobs: JSON.stringify(OperateWorkerJobService$Wonderjs.getWorkerJobs(state[/* workerJobRecord */3]))
                    }, WorkerInstanceService$Wonderjs.unsafeGetRenderWorker(state[/* workerInstanceRecord */33]));
                return /* Some */[operateType];
              }));
}

export {
  execJob ,
  
}
/* MostUtils-Wonderjs Not a pure module */
