// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as SparseMapService$WonderCommonlib from "../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/SparseMapService.js";

var isDisposed = SparseMapService$WonderCommonlib.has;

export {
  isDisposed ,
  
}
/* No side effect */
