// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as SparseMapSystem$Wonderjs from "../../../structure/SparseMapSystem.js";

function copyFloat32Array(typeArr) {
  if (typeArr === undefined) {
    return undefined;
  } else {
    return typeArr.slice();
  }
}

function deepCopyFloat32ArrayArray(arr) {
  return arr.map(copyFloat32Array);
}

function deepCopyArrayArray(arr) {
  return arr.map((function (itemArr) {
                var match = SparseMapSystem$Wonderjs.isDeleted(itemArr);
                if (match !== 0) {
                  return undefined;
                } else {
                  return itemArr.slice();
                }
              }));
}

function copyArrayBuffer(buffer) {
  return buffer.slice(0);
}

function copyFloat32TypeArrayFromBuffer(buffer) {
  return new Float32Array(buffer);
}

function copyFloat32TypeArrayFromBufferRange(buffer, offset, length) {
  return new Float32Array(buffer, offset, length);
}

function copyUint8TypeArrayFromBuffer(buffer) {
  return new Uint8Array(buffer);
}

export {
  copyFloat32Array                    ,
  deepCopyFloat32ArrayArray           ,
  deepCopyArrayArray                  ,
  copyArrayBuffer                     ,
  copyFloat32TypeArrayFromBuffer      ,
  copyFloat32TypeArrayFromBufferRange ,
  copyUint8TypeArrayFromBuffer        ,
  
}
/* SparseMapSystem-Wonderjs Not a pure module */
