// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE


function create() {
  return /* record */[
          /* extensionInstancedArrays : None */0,
          /* precision : None */0,
          /* maxTextureUnit : None */0
        ];
}

export {
  create ,
  
}
/* No side effect */
