// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as PoolVboBufferService$Wonderjs from "../../../record/main/vboBuffer/PoolVboBufferService.js";

function restore(currentState, targetState) {
  var match = PoolVboBufferService$Wonderjs.addAllBufferToPool(currentState[/* vboBufferRecord */31]);
  var newrecord = targetState.slice();
  newrecord[/* vboBufferRecord */31] = /* record */[
    /* boxGeometryVertexBufferMap : array */[],
    /* boxGeometryNormalBufferMap : array */[],
    /* boxGeometryElementArrayBufferMap : array */[],
    /* customGeometryVertexBufferMap : array */[],
    /* customGeometryNormalBufferMap : array */[],
    /* customGeometryElementArrayBufferMap : array */[],
    /* matrixInstanceBufferMap : array */[],
    /* vertexArrayBufferPool */match[0],
    /* elementArrayBufferPool */match[1],
    /* matrixInstanceBufferPool */match[2]
  ];
  return newrecord;
}

export {
  restore ,
  
}
/* PoolVboBufferService-Wonderjs Not a pure module */
