// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as RestoreShaderFromStateService$Wonderjs from "../../../primitiive/shader/RestoreShaderFromStateService.js";

function restore(intersectShaderIndexDataArray, currentState, targetState) {
  var match = currentState[/* programRecord */24];
  var newrecord = targetState.slice();
  newrecord[/* programRecord */24] = /* record */[
    /* programMap */RestoreShaderFromStateService$Wonderjs.getIntersectShaderRelatedMap(intersectShaderIndexDataArray, match[/* programMap */0]),
    /* lastUsedProgram : None */0
  ];
  return newrecord;
}

export {
  restore ,
  
}
/* RestoreShaderFromStateService-Wonderjs Not a pure module */
