// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as GameObjectGetComponentCommon$Wonderjs           from "./GameObjectGetComponentCommon.js";
import * as GeometryDisposeComponentCommon$Wonderjs         from "../component/system/geometry/GeometryDisposeComponentCommon.js";
import * as MaterialDisposeComponentCommon$Wonderjs         from "../component/system/material/MaterialDisposeComponentCommon.js";
import * as TransformDisposeComponentCommon$Wonderjs        from "../component/system/transform/TransformDisposeComponentCommon.js";
import * as MeshRendererDisposeComponentCommon$Wonderjs     from "../component/system/meshRenderer/MeshRendererDisposeComponentCommon.js";
import * as ObjectInstanceDisposeComponentCommon$Wonderjs   from "../component/system/instance/objectInstance/ObjectInstanceDisposeComponentCommon.js";
import * as SourceInstanceDisposeComponentCommon$Wonderjs   from "../component/system/instance/sourceInstance/SourceInstanceDisposeComponentCommon.js";
import * as CameraControllerDisposeComponentCommon$Wonderjs from "../component/system/cameraController/CameraControllerDisposeComponentCommon.js";

function disposeSourceInstanceComponent(_, component, batchDisposeGameObjectFunc, state) {
  return SourceInstanceDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, batchDisposeGameObjectFunc, state);
}

function disposeObjectInstanceComponent(_, component, state) {
  return ObjectInstanceDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeCameraControllerComponent(_, component, state) {
  return CameraControllerDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeTransformComponent(_, component, state) {
  return TransformDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeGeometryComponent(_, component, state) {
  return GeometryDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeMeshRendererComponent(uid, component, state) {
  return MeshRendererDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, uid, state);
}

function disposeMaterialComponent(_, component, state) {
  return MaterialDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function _batchDisposeComponent(uidMap, state, handleFunc, componentArray) {
  return handleFunc(componentArray, uidMap, state);
}

function batchDisposeTransformComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, TransformDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeMeshRendererComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, MeshRendererDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeMaterialComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, MaterialDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeGeometryComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, GeometryDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeCameraControllerComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, CameraControllerDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeSourceInstanceComponent(uidMap, state, disposeGameObjectFunc, componentArray) {
  return SourceInstanceDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent(componentArray, uidMap, disposeGameObjectFunc, state);
}

function batchDisposeObjectInstanceComponent(uidMap, state, componentArray) {
  var match = componentArray.length;
  if (match !== 0) {
    return _batchDisposeComponent(uidMap, state, ObjectInstanceDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
  } else {
    return state;
  }
}

function disposeComponent(uid, batchDisposeFunc, state) {
  var match = GameObjectGetComponentCommon$Wonderjs.getTransformComponent(uid, state);
  var state$1 = match ? TransformDisposeComponentCommon$Wonderjs.handleDisposeComponent(match[0], state) : state;
  var match$1 = GameObjectGetComponentCommon$Wonderjs.getMeshRendererComponent(uid, state$1);
  var state$2 = match$1 ? MeshRendererDisposeComponentCommon$Wonderjs.handleDisposeComponent(match$1[0], uid, state$1) : state$1;
  var match$2 = GameObjectGetComponentCommon$Wonderjs.getMaterialComponent(uid, state$2);
  var state$3 = match$2 ? MaterialDisposeComponentCommon$Wonderjs.handleDisposeComponent(match$2[0], state$2) : state$2;
  var match$3 = GameObjectGetComponentCommon$Wonderjs.getGeometryComponent(uid, state$3);
  var state$4 = match$3 ? GeometryDisposeComponentCommon$Wonderjs.handleDisposeComponent(match$3[0], state$3) : state$3;
  var match$4 = GameObjectGetComponentCommon$Wonderjs.getCameraControllerComponent(uid, state$4);
  var state$5 = match$4 ? CameraControllerDisposeComponentCommon$Wonderjs.handleDisposeComponent(match$4[0], state$4) : state$4;
  var match$5 = GameObjectGetComponentCommon$Wonderjs.getSourceInstanceComponent(uid, state$5);
  var state$6 = match$5 ? SourceInstanceDisposeComponentCommon$Wonderjs.handleDisposeComponent(match$5[0], batchDisposeFunc, state$5) : state$5;
  var match$6 = GameObjectGetComponentCommon$Wonderjs.getObjectInstanceComponent(uid, state$6);
  if (match$6) {
    return ObjectInstanceDisposeComponentCommon$Wonderjs.handleDisposeComponent(match$6[0], state$6);
  } else {
    return state$6;
  }
}

function batchDisposeCommonComponent(uidArray, disposedUidMap, batchDisposeFunc, state) {
  return batchDisposeSourceInstanceComponent(disposedUidMap, state, batchDisposeFunc, GameObjectGetComponentCommon$Wonderjs.batchGetSourceInstanceComponent(uidArray, batchDisposeObjectInstanceComponent(disposedUidMap, state, GameObjectGetComponentCommon$Wonderjs.batchGetObjectInstanceComponent(uidArray, batchDisposeCameraControllerComponent(disposedUidMap, state, GameObjectGetComponentCommon$Wonderjs.batchGetCameraControllerComponent(uidArray, batchDisposeGeometryComponent(disposedUidMap, state, GameObjectGetComponentCommon$Wonderjs.batchGetGeometryComponent(uidArray, batchDisposeMaterialComponent(disposedUidMap, state, GameObjectGetComponentCommon$Wonderjs.batchGetMaterialComponent(uidArray, batchDisposeTransformComponent(disposedUidMap, state, GameObjectGetComponentCommon$Wonderjs.batchGetTransformComponent(uidArray, batchDisposeMeshRendererComponent(disposedUidMap, state, GameObjectGetComponentCommon$Wonderjs.batchGetMeshRendererComponent(uidArray, state))))))))))))));
}

export {
  disposeSourceInstanceComponent        ,
  disposeObjectInstanceComponent        ,
  disposeCameraControllerComponent      ,
  disposeTransformComponent             ,
  disposeGeometryComponent              ,
  disposeMeshRendererComponent          ,
  disposeMaterialComponent              ,
  _batchDisposeComponent                ,
  batchDisposeTransformComponent        ,
  batchDisposeMeshRendererComponent     ,
  batchDisposeMaterialComponent         ,
  batchDisposeGeometryComponent         ,
  batchDisposeCameraControllerComponent ,
  batchDisposeSourceInstanceComponent   ,
  batchDisposeObjectInstanceComponent   ,
  disposeComponent                      ,
  batchDisposeCommonComponent           ,
  
}
/* GameObjectGetComponentCommon-Wonderjs Not a pure module */
