// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as GeometryDisposeComponentCommon$Wonderjs         from "../component/system/geometry/GeometryDisposeComponentCommon.js";
import * as MaterialDisposeComponentCommon$Wonderjs         from "../component/system/material/MaterialDisposeComponentCommon.js";
import * as TransformDisposeComponentCommon$Wonderjs        from "../component/system/transform/TransformDisposeComponentCommon.js";
import * as MeshRendererDisposeComponentCommon$Wonderjs     from "../component/system/meshRenderer/MeshRendererDisposeComponentCommon.js";
import * as ObjectInstanceDisposeComponentCommon$Wonderjs   from "../component/system/instance/objectInstance/ObjectInstanceDisposeComponentCommon.js";
import * as SourceInstanceDisposeComponentCommon$Wonderjs   from "../component/system/instance/sourceInstance/SourceInstanceDisposeComponentCommon.js";
import * as CameraControllerDisposeComponentCommon$Wonderjs from "../component/system/cameraController/CameraControllerDisposeComponentCommon.js";

function disposeSourceInstanceComponent(_, component, batchDisposeGameObjectFunc, state) {
  return SourceInstanceDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, batchDisposeGameObjectFunc, state);
}

function disposeObjectInstanceComponent(_, component, state) {
  return ObjectInstanceDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeCameraControllerComponent(_, component, state) {
  return CameraControllerDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeTransformComponent(_, component, state) {
  return TransformDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeGeometryComponent(_, component, state) {
  return GeometryDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function disposeMeshRendererComponent(uid, component, state) {
  return MeshRendererDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, uid, state);
}

function disposeMaterialComponent(_, component, state) {
  return MaterialDisposeComponentCommon$Wonderjs.handleDisposeComponent(component, state);
}

function _batchDisposeComponent(uidMap, state, handleFunc, componentArray) {
  return handleFunc(componentArray, uidMap, state);
}

function batchDisposeTransformComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, TransformDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeMeshRendererComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, MeshRendererDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeMaterialComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, MaterialDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeGeometryComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, GeometryDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeCameraControllerComponent(uidMap, state, componentArray) {
  return _batchDisposeComponent(uidMap, state, CameraControllerDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
}

function batchDisposeSourceInstanceComponent(uidMap, state, disposeGameObjectFunc, componentArray) {
  return SourceInstanceDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent(componentArray, uidMap, disposeGameObjectFunc, state);
}

function batchDisposeObjectInstanceComponent(uidMap, state, componentArray) {
  var match = componentArray.length;
  if (match !== 0) {
    return _batchDisposeComponent(uidMap, state, ObjectInstanceDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent, componentArray);
  } else {
    return state;
  }
}

export {
  disposeSourceInstanceComponent        ,
  disposeObjectInstanceComponent        ,
  disposeCameraControllerComponent      ,
  disposeTransformComponent             ,
  disposeGeometryComponent              ,
  disposeMeshRendererComponent          ,
  disposeMaterialComponent              ,
  _batchDisposeComponent                ,
  batchDisposeTransformComponent        ,
  batchDisposeMeshRendererComponent     ,
  batchDisposeMaterialComponent         ,
  batchDisposeGeometryComponent         ,
  batchDisposeCameraControllerComponent ,
  batchDisposeSourceInstanceComponent   ,
  batchDisposeObjectInstanceComponent   ,
  
}
/* GeometryDisposeComponentCommon-Wonderjs Not a pure module */
