declare function pipe<A>(): (arg: A) => A;
declare function pipe<A, B>(fn: (arg: A) => B): (arg: A) => B;
declare function pipe<A, B, C>(fn0: (arg: A) => B, fn1: (arg: B) => C): (arg: A) => C;
declare function pipe<A, B, C, D>(fn0: (arg: A) => B, fn1: (arg: B) => C, fn2: (arg: C) => D): (arg: A) => D;
declare function pipe<A, B, C, D, E>(fn0: (arg: A) => B, fn1: (arg: B) => C, fn2: (arg: C) => D, fn3: (arg: D) => E): (arg: A) => E;
declare function pipe<A, B, C, D, E, F>(fn0: (arg: A) => B, fn1: (arg: B) => C, fn2: (arg: C) => D, fn3: (arg: D) => E, fn4: (arg: E) => F): (arg: A) => F;
declare function pipe<A, B, C, D, E, F, G>(fn0: (arg: A) => B, fn1: (arg: B) => C, fn2: (arg: C) => D, fn3: (arg: D) => E, fn4: (arg: E) => F, fn5: (arg: F) => G): (arg: A) => G;
declare function pipe<A, B, C, D, E, F, G, H>(fn0: (arg: A) => B, fn1: (arg: B) => C, fn2: (arg: C) => D, fn3: (arg: D) => E, fn4: (arg: E) => F, fn5: (arg: F) => G, fn6: (arg: G) => H): (arg: A) => H;
declare function pipe<A, B, C, D, E, F, G, H, I>(fn0: (arg: A) => B, fn1: (arg: B) => C, fn2: (arg: C) => D, fn3: (arg: D) => E, fn4: (arg: E) => F, fn5: (arg: F) => G, fn6: (arg: G) => H, fn7: (arg: H) => I): (arg: A) => I;
export default pipe;
