// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Contract$WonderLog                       from "../../../../../node_modules/wonder-log/lib/es6_global/src/Contract.js";
import * as MainStateData$Wonderjs                   from "../../service/state/main/data/MainStateData.js";
import * as IsDebugMainService$Wonderjs              from "../../service/state/main/state/IsDebugMainService.js";
import * as AliveComponentService$Wonderjs           from "../../service/primitiive/component/AliveComponentService.js";
import * as DisposeBasicMaterialService$Wonderjs     from "../../service/record/material/basic/DisposeBasicMaterialService.js";
import * as CreateBasicMaterialMainService$Wonderjs  from "../../service/state/main/material/basic/CreateBasicMaterialMainService.js";
import * as GameObjectBasicMaterialService$Wonderjs  from "../../service/record/material/basic/GameObjectBasicMaterialService.js";
import * as OperateBasicMaterialMainService$Wonderjs from "../../service/state/main/material/basic/OperateBasicMaterialMainService.js";

function createBasicMaterial(state) {
  return CreateBasicMaterialMainService$Wonderjs.create(state);
}

function unsafeGetBasicMaterialGameObject(material, state) {
  Contract$WonderLog.requireCheck((function () {
          return AliveComponentService$Wonderjs.checkComponentShouldAlive(material, DisposeBasicMaterialService$Wonderjs.isAlive, state[/* basicMaterialRecord */15]);
        }), IsDebugMainService$Wonderjs.getIsDebug(MainStateData$Wonderjs.stateData));
  return GameObjectBasicMaterialService$Wonderjs.unsafeGetGameObject(material, state[/* basicMaterialRecord */15]);
}

function unsafeGetBasicMaterialColor(material, state) {
  Contract$WonderLog.requireCheck((function () {
          return AliveComponentService$Wonderjs.checkComponentShouldAlive(material, DisposeBasicMaterialService$Wonderjs.isAlive, state[/* basicMaterialRecord */15]);
        }), IsDebugMainService$Wonderjs.getIsDebug(MainStateData$Wonderjs.stateData));
  return OperateBasicMaterialMainService$Wonderjs.unsafeGetColor(material, state);
}

function setBasicMaterialColor(material, color, state) {
  Contract$WonderLog.requireCheck((function () {
          return AliveComponentService$Wonderjs.checkComponentShouldAlive(material, DisposeBasicMaterialService$Wonderjs.isAlive, state[/* basicMaterialRecord */15]);
        }), IsDebugMainService$Wonderjs.getIsDebug(MainStateData$Wonderjs.stateData));
  return OperateBasicMaterialMainService$Wonderjs.setColor(material, color, state);
}

export {
  createBasicMaterial              ,
  unsafeGetBasicMaterialGameObject ,
  unsafeGetBasicMaterialColor      ,
  setBasicMaterialColor            ,
  
}
/* Contract-WonderLog Not a pure module */
