// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ComponentSystem$Wonderjs         from "../component/ComponentSystem.js";
import * as MeshRendererStateCommon$Wonderjs from "./MeshRendererStateCommon.js";

function create(state) {
  var data = MeshRendererStateCommon$Wonderjs.getMeshRendererData(state);
  var index = data[/* index */0];
  var disposedIndexArray = data[/* disposedIndexArray */3];
  var match = ComponentSystem$Wonderjs.generateIndex(index, disposedIndexArray);
  data[/* index */0] = match[1];
  return /* tuple */[
          state,
          match[0]
        ];
}

export {
  create ,
  
}
/* MeshRendererStateCommon-Wonderjs Not a pure module */
