// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ComputePointsBoxGeometryService$Wonderjs from "../../../../record/main/geometry/box/ComputePointsBoxGeometryService.js";

function getIndices(_, param) {
  return param[/* boxGeometryRecord */4][/* indices */2];
}

function getIndicesCount(_, _$1) {
  return ComputePointsBoxGeometryService$Wonderjs.getIndicesCount(/* () */0);
}

export {
  getIndices      ,
  getIndicesCount ,
  
}
/* ComputePointsBoxGeometryService-Wonderjs Not a pure module */
