// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE


function getNormals(_, param) {
  return param[/* boxGeometryRecord */5][/* normals */2];
}

export {
  getNormals ,
  
}
/* No side effect */
