// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as OptionService$Wonderjs from "../../../atom/OptionService.js";

function getCanvas(param) {
  return OptionService$Wonderjs.unsafeGet(param[/* canvas */0]);
}

function setCanvas(canvas, _) {
  return /* record */[/* canvas : Some */[canvas]];
}

export {
  getCanvas ,
  setCanvas ,
  
}
/* OptionService-Wonderjs Not a pure module */
