// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Json_decode from "../../../../../../../node_modules/bs-json/lib/es6_global/src/Json_decode.js";

function convertSettingToRecord(setting) {
  return /* record */[
          /* workerFileDir */Json_decode.field("worker_file_dir", Json_decode.string, setting),
          /* mainInitPipeline */Json_decode.field("main_init_pipeline", Json_decode.string, setting),
          /* mainLoopPipeline */Json_decode.field("main_loop_pipeline", Json_decode.string, setting),
          /* workerPipeline */Json_decode.field("worker_pipeline", Json_decode.string, setting)
        ];
}

function convertMainInitPipelinesToRecord(pipelines) {
  return Json_decode.array((function (json) {
                return /* record */[
                        /* name */Json_decode.field("name", Json_decode.string, json),
                        /* jobs */Json_decode.field("jobs", (function (json) {
                                return Json_decode.array((function (json) {
                                              return /* record */[
                                                      /* name */Json_decode.field("name", Json_decode.string, json),
                                                      /* link */Json_decode.field("link", Json_decode.string, json),
                                                      /* jobs */Json_decode.field("jobs", (function (json) {
                                                              return Json_decode.array((function (json) {
                                                                            return /* record */[/* name */Json_decode.field("name", Json_decode.string, json)];
                                                                          }), json);
                                                            }), json)
                                                    ];
                                            }), json);
                              }), json)
                      ];
              }), pipelines);
}

function convertMainLoopPipelinesToRecord(pipelines) {
  return Json_decode.array((function (json) {
                return /* record */[
                        /* name */Json_decode.field("name", Json_decode.string, json),
                        /* jobs */Json_decode.field("jobs", (function (json) {
                                return Json_decode.array((function (json) {
                                              return /* record */[
                                                      /* name */Json_decode.field("name", Json_decode.string, json),
                                                      /* link */Json_decode.field("link", Json_decode.string, json),
                                                      /* jobs */Json_decode.field("jobs", (function (json) {
                                                              return Json_decode.array((function (json) {
                                                                            return /* record */[/* name */Json_decode.field("name", Json_decode.string, json)];
                                                                          }), json);
                                                            }), json)
                                                    ];
                                            }), json);
                              }), json)
                      ];
              }), pipelines);
}

function convertWorkerPipelinesToRecord(pipelines) {
  return Json_decode.array((function (json) {
                return /* record */[
                        /* name */Json_decode.field("name", Json_decode.string, json),
                        /* jobs */Json_decode.field("jobs", (function (json) {
                                return /* record */[/* render */Json_decode.field("render", (function (json) {
                                                return Json_decode.array((function (json) {
                                                              return Json_decode.array((function (json) {
                                                                            return /* record */[/* name */Json_decode.field("name", Json_decode.string, json)];
                                                                          }), json);
                                                            }), json);
                                              }), json)];
                              }), json)
                      ];
              }), pipelines);
}

function _convertJobsToRecord(jobs) {
  return Json_decode.array((function (json) {
                return /* record */[
                        /* name */Json_decode.field("name", Json_decode.string, json),
                        /* flags */Json_decode.optional((function (param) {
                                return Json_decode.field("flags", (function (json) {
                                              return Json_decode.array(Json_decode.string, json);
                                            }), param);
                              }), json)
                      ];
              }), jobs);
}

var convertMainInitJobsToRecord = _convertJobsToRecord;

var convertMainLoopJobsToRecord = _convertJobsToRecord;

var convertWorkerJobsToRecord = _convertJobsToRecord;

export {
  convertSettingToRecord           ,
  convertMainInitPipelinesToRecord ,
  convertMainLoopPipelinesToRecord ,
  convertWorkerPipelinesToRecord   ,
  _convertJobsToRecord             ,
  convertMainInitJobsToRecord      ,
  convertMainLoopJobsToRecord      ,
  convertWorkerJobsToRecord        ,
  
}
/* No side effect */
