module wd{
    export enum EShaderMapKeyOfScene{
        BUILD_TWOD_SHADOWMAP_INSTANCE = <any>"BUILD_TWOD_SHADOWMAP_INSTANCE",
        BUILD_TWOD_SHADOWMAP_NO_INSTANCE = <any>"BUILD_TWOD_SHADOWMAP_NO_INSTANCE",
        BUILD_CUBEMAP_SHADOWMAP_INSTANCE = <any>"BUILD_CUBEMAP_SHADOWMAP_INSTANCE",
        BUILD_CUBEMAP_SHADOWMAP_NO_INSTANCE = <any>"BUILD_CUBEMAP_SHADOWMAP_NO_INSTANCE"
    }
}
