// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as LightIndexCommon$Wonderjs            from "../LightIndexCommon.js";
import * as PointLightHelper$Wonderjs            from "../../../data/light/point/PointLightHelper.js";
import * as PointLightIndexCommon$Wonderjs       from "./PointLightIndexCommon.js";
import * as PointLightStateCommon$Wonderjs       from "./PointLightStateCommon.js";
import * as LightDisposeComponentCommon$Wonderjs from "../LightDisposeComponentCommon.js";

function isAlive(light, state) {
  return LightDisposeComponentCommon$Wonderjs.isAlive(light, PointLightIndexCommon$Wonderjs.getMappedIndexMap(state));
}

function _disposeData(sourceIndex, data) {
  var mappedIndexMap = data[/* mappedIndexMap */8];
  var index = data[/* index */0];
  var gameObjectMap = LightDisposeComponentCommon$Wonderjs.disposeData(sourceIndex, data[/* gameObjectMap */9]);
  var lastComponentIndex = index - 1 | 0;
  var mappedSourceIndex = LightIndexCommon$Wonderjs.getMappedIndex(sourceIndex, mappedIndexMap);
  return /* record */[
          /* index */index - 1 | 0,
          /* buffer */data[/* buffer */1],
          /* colors */LightDisposeComponentCommon$Wonderjs.swapData(/* tuple */[
                mappedSourceIndex,
                lastComponentIndex
              ], /* tuple */[
                mappedIndexMap,
                PointLightHelper$Wonderjs.getColorDataSize(/* () */0),
                PointLightHelper$Wonderjs.getDefaultColor(/* () */0)
              ], LightDisposeComponentCommon$Wonderjs.deleteBySwapAndResetFloat32TypeArr, data[/* colors */2]),
          /* intensities */LightDisposeComponentCommon$Wonderjs.swapData(/* tuple */[
                mappedSourceIndex,
                lastComponentIndex
              ], /* tuple */[
                mappedIndexMap,
                PointLightHelper$Wonderjs.getIntensityDataSize(/* () */0),
                PointLightHelper$Wonderjs.getDefaultIntensity(/* () */0)
              ], LightDisposeComponentCommon$Wonderjs.deleteSingleValueBySwapAndResetFloat32TypeArr, data[/* intensities */3]),
          /* constants */LightDisposeComponentCommon$Wonderjs.swapData(/* tuple */[
                mappedSourceIndex,
                lastComponentIndex
              ], /* tuple */[
                mappedIndexMap,
                PointLightHelper$Wonderjs.getConstantDataSize(/* () */0),
                PointLightHelper$Wonderjs.getDefaultConstant(/* () */0)
              ], LightDisposeComponentCommon$Wonderjs.deleteSingleValueBySwapAndResetFloat32TypeArr, data[/* constants */4]),
          /* linears */LightDisposeComponentCommon$Wonderjs.swapData(/* tuple */[
                mappedSourceIndex,
                lastComponentIndex
              ], /* tuple */[
                mappedIndexMap,
                PointLightHelper$Wonderjs.getLinearDataSize(/* () */0),
                PointLightHelper$Wonderjs.getDefaultLinear(/* () */0)
              ], LightDisposeComponentCommon$Wonderjs.deleteSingleValueBySwapAndResetFloat32TypeArr, data[/* linears */5]),
          /* quadratics */LightDisposeComponentCommon$Wonderjs.swapData(/* tuple */[
                mappedSourceIndex,
                lastComponentIndex
              ], /* tuple */[
                mappedIndexMap,
                PointLightHelper$Wonderjs.getQuadraticDataSize(/* () */0),
                PointLightHelper$Wonderjs.getDefaultQuadratic(/* () */0)
              ], LightDisposeComponentCommon$Wonderjs.deleteSingleValueBySwapAndResetFloat32TypeArr, data[/* quadratics */6]),
          /* ranges */LightDisposeComponentCommon$Wonderjs.swapData(/* tuple */[
                mappedSourceIndex,
                lastComponentIndex
              ], /* tuple */[
                mappedIndexMap,
                PointLightHelper$Wonderjs.getRangeDataSize(/* () */0),
                PointLightHelper$Wonderjs.getDefaultRange(/* () */0)
              ], LightDisposeComponentCommon$Wonderjs.deleteSingleValueBySwapAndResetFloat32TypeArr, data[/* ranges */7]),
          /* mappedIndexMap */LightDisposeComponentCommon$Wonderjs.setMappedIndexMap(sourceIndex, mappedSourceIndex, lastComponentIndex, mappedIndexMap),
          /* gameObjectMap */gameObjectMap
        ];
}

function _handleDispose(light, state) {
  var newrecord = state.slice();
  newrecord[/* pointLightData */19] = _disposeData(light, PointLightStateCommon$Wonderjs.getLightData(state));
  return newrecord;
}

function handleDisposeComponent(light, state) {
  return LightDisposeComponentCommon$Wonderjs.handleDisposeComponent(light, /* tuple */[
              isAlive,
              _handleDispose
            ], state);
}

function handleBatchDisposeComponent(lightArray, _, state) {
  return LightDisposeComponentCommon$Wonderjs.handleBatchDisposeComponent(lightArray, /* tuple */[
              isAlive,
              _handleDispose
            ], state);
}

export {
  isAlive                     ,
  _disposeData                ,
  _handleDispose              ,
  handleDisposeComponent      ,
  handleBatchDisposeComponent ,
  
}
/* PointLightHelper-Wonderjs Not a pure module */
