// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Log$WonderLog                                 from "../../../../../../../node_modules/wonder-log/lib/es6_global/src/Log.js";
import * as ArrayService$Wonderjs                         from "../../../atom/ArrayService.js";
import * as ArrayService$WonderCommonlib                  from "../../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/ArrayService.js";
import * as ComponentMapService$Wonderjs                  from "../../../primitive/gameObject/ComponentMapService.js";
import * as CurrentComponentDataMapRenderService$Wonderjs from "../../render/gameObject/CurrentComponentDataMapRenderService.js";

function batchGetBasicCameraViewComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* basicCameraViewMap */23]);
}

function batchGetPerspectiveCameraProjectionComponent(uidArray, state) {
  var gameObjectRecord = state[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* perspectiveCameraProjectionMap */24]);
}

function batchGetTransformComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* transformMap */22]);
}

function batchGetGeometryComponentData(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  var currentGeometryDataMap = gameObjectRecord[/* currentGeometryDataMap */21];
  var boxGeometryType = CurrentComponentDataMapRenderService$Wonderjs.getBoxGeometryType(/* () */0);
  var customGeometryType = CurrentComponentDataMapRenderService$Wonderjs.getCustomGeometryType(/* () */0);
  return ArrayService$WonderCommonlib.reduceOneParam((function (arrTuple, uid) {
                var match = CurrentComponentDataMapRenderService$Wonderjs.getComponentData(uid, currentGeometryDataMap);
                if (match) {
                  var match$1 = match[0];
                  var type_ = match$1[1];
                  var component = match$1[0];
                  if (type_ === boxGeometryType) {
                    ArrayService$Wonderjs.push(component, arrTuple[0]);
                  } else if (type_ === customGeometryType) {
                    ArrayService$Wonderjs.push(component, arrTuple[1]);
                  } else {
                    Log$WonderLog.fatal(Log$WonderLog.buildFatalMessage("unknown type_", "", "", "", "type_: " + (String(type_) + "")));
                  }
                  return arrTuple;
                } else {
                  return arrTuple;
                }
              }), /* tuple */[
              /* int array */[],
              /* int array */[]
            ], uidArray);
}

function batchGetBasicMaterialComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* basicMaterialMap */26]);
}

function batchGetLightMaterialComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* lightMaterialMap */27]);
}

function batchGetMeshRendererComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* meshRendererMap */25]);
}

function batchGetAmbientLightComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* ambientLightMap */30]);
}

function batchGetDirectionLightComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* directionLightMap */31]);
}

function batchGetPointLightComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* pointLightMap */32]);
}

function batchGetSourceInstanceComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* sourceInstanceMap */28]);
}

function batchGetObjectInstanceComponent(uidArray, param) {
  var gameObjectRecord = param[/* gameObjectRecord */10];
  return ComponentMapService$Wonderjs.batchGetComponent(uidArray, gameObjectRecord[/* objectInstanceMap */29]);
}

export {
  batchGetBasicCameraViewComponent             ,
  batchGetPerspectiveCameraProjectionComponent ,
  batchGetTransformComponent                   ,
  batchGetGeometryComponentData                ,
  batchGetBasicMaterialComponent               ,
  batchGetLightMaterialComponent               ,
  batchGetMeshRendererComponent                ,
  batchGetAmbientLightComponent                ,
  batchGetDirectionLightComponent              ,
  batchGetPointLightComponent                  ,
  batchGetSourceInstanceComponent              ,
  batchGetObjectInstanceComponent              ,
  
}
/* Log-WonderLog Not a pure module */
