// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function getVboBufferData(state) {
  return state[/* vboBufferData */29];
}

export {
  getVboBufferData ,
  
}
/* No side effect */
