// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Most                    from "most";
import * as Js_boolean              from "../../../../../../node_modules/bs-platform/lib/es6/js_boolean.js";
import * as JobConfigUtils$Wonderjs from "./JobConfigUtils.js";

function _createGetWorkerDataStream(flags, target) {
  return Most.filter((function (e) {
                return Js_boolean.to_js_boolean(+(e.data.operateType === JobConfigUtils$Wonderjs.getOperateType(flags)));
              }), Most.fromEvent("message", target));
}

function createGetMainWorkerDataStream(flags, target) {
  return Most.map((function (e) {
                return /* Some */[e];
              }), _createGetWorkerDataStream(flags, target));
}

function createGetOtherWorkerDataStream(flags, target) {
  return Most.map((function () {
                return /* None */0;
              }), Most.take(1, _createGetWorkerDataStream(flags, target)));
}

export {
  _createGetWorkerDataStream     ,
  createGetMainWorkerDataStream  ,
  createGetOtherWorkerDataStream ,
  
}
/* most Not a pure module */
