// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function create() {
  return /* record */[/* currentCameraGameObject : None */0];
}

export {
  create ,
  
}
/* No side effect */
