// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function create() {
  return /* record */[
          /* float16Array1 */new Float32Array(/* float array */[
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                1
              ]),
          /* float9Array1 */new Float32Array(/* float array */[
                1,
                0,
                0,
                1,
                0,
                0,
                1,
                0,
                0
              ])
        ];
}

export {
  create ,
  
}
/* No side effect */
