// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as GetCameraDataJobUtils$Wonderjs    from "../../utils/GetCameraDataJobUtils.js";
import * as OperateRenderMainService$Wonderjs from "../../../service/state/main/render/OperateRenderMainService.js";

function execJob(_, state) {
  return OperateRenderMainService$Wonderjs.setCameraRecord(GetCameraDataJobUtils$Wonderjs.getCameraData(state), state);
}

export {
  execJob ,
  
}
/* GetCameraDataJobUtils-Wonderjs Not a pure module */
