open GlType;

open Gl;

open GameObjectType;

open StateDataType;

open GLSLSenderStateUtils;

open GLSLSenderSendDataUtils;

open GLSLSenderDrawUtils;

let addAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.addAttributeSendData;

let addUniformSendData = GLSLSenderConfigDataHandleUniformCommon.addUniformSendData;

let unsafeGetAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.unsafeGetAttributeSendData;

let unsafeGetInstanceAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.unsafeGetInstanceAttributeSendData;

let unsafeGetUniformRenderObjectSendMaterialData = GLSLSenderConfigDataHandleUniformCommon.unsafeGetUniformRenderObjectSendMaterialData;

let unsafeGetUniformRenderObjectSendModelData = GLSLSenderConfigDataHandleUniformCommon.unsafeGetUniformRenderObjectSendModelData;

let unsafeGetUniformShaderSendNoCachableData = GLSLSenderConfigDataHandleUniformCommon.unsafeGetUniformShaderSendNoCachableData;

let unsafeGetUniformShaderSendCachableFunctionData = GLSLSenderConfigDataHandleUniformCommon.unsafeGetUniformShaderSendCachableFunctionData;

let unsafeGetUniformInstanceSendNoCachableData = GLSLSenderConfigDataHandleUniformCommon.unsafeGetUniformInstanceSendNoCachableData;