open GlType;

open Gl;

open GameObjectType;

open StateDataType;

open Contract;

open GLSLSenderStateUtils;

open GLSLSenderSendDataUtils;

open GLSLSenderDrawUtils;

let addAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.addAttributeSendData;

let addUniformSendData = GLSLSenderConfigDataHandleUniformCommon.addUniformSendData;

let getAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.getAttributeSendData;

let getInstanceAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.getInstanceAttributeSendData;

let getUniformSendNoCacheableData = GLSLSenderConfigDataHandleUniformCommon.getUniformSendNoCacheableData;

let getUniformSendCacheableData = GLSLSenderConfigDataHandleUniformCommon.getUniformSendCacheableData;

let getShaderUniformSendNoCacheableData = GLSLSenderConfigDataHandleUniformCommon.getShaderUniformSendNoCacheableData;

let getInstanceUniformSendNoCacheableData = GLSLSenderConfigDataHandleUniformCommon.getInstanceUniformSendNoCacheableData;