open GlType;

open Gl;

open GameObjectType;

open StateDataType;

open GLSLSenderStateUtils;

open GLSLSenderSendDataUtils;

open GLSLSenderDrawUtils;

let addAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.addAttributeSendData;

let addUniformSendData = GLSLSenderConfigDataHandleUniformCommon.addUniformSendData;

let getAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.getAttributeSendData;

let getInstanceAttributeSendData = GLSLSenderConfigDataHandleAttributeCommon.getInstanceAttributeSendData;

let getUniformSendNoCachableData = GLSLSenderConfigDataHandleUniformCommon.getUniformSendNoCachableData;

let getUniformSendCachableData = GLSLSenderConfigDataHandleUniformCommon.getUniformSendCachableData;

let getShaderUniformSendNoCachableData = GLSLSenderConfigDataHandleUniformCommon.getShaderUniformSendNoCachableData;

let getInstanceUniformSendNoCachableData = GLSLSenderConfigDataHandleUniformCommon.getInstanceUniformSendNoCachableData;