// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var GameObjectAPI$Wonderjs = require("../../../../src/api/GameObjectAPI.js");
var VboBufferTool$Wonderjs = require("../../../tool/service/vboBuffer/VboBufferTool.js");
var BoxGeometryAPI$Wonderjs = require("../../../../src/api/geometry/BoxGeometryAPI.js");
var BoxGeometryTool$Wonderjs = require("../../../tool/service/geometry/BoxGeometryTool.js");
var MeshRendererTool$Wonderjs = require("../../../tool/service/meshRenderer/MeshRendererTool.js");
var CustomGeometryTool$Wonderjs = require("../../../tool/service/geometry/CustomGeometryTool.js");

function prepareForDisposeBoxGeometryVboBuffer(state) {
  var match = BoxGeometryTool$Wonderjs.createGameObject(state[0]);
  var geometry1 = match[2];
  var gameObject1 = match[1];
  var state$1 = VboBufferTool$Wonderjs.addVboBufferToBoxGeometryBufferMap(geometry1, match[0]);
  var state$2 = GameObjectAPI$Wonderjs.disposeGameObject(gameObject1, state$1);
  return /* tuple */[
          state$2,
          gameObject1,
          geometry1
        ];
}

function prepareForDisposeGameObjects(state) {
  var match = MeshRendererTool$Wonderjs.createBasicMaterialGameObject(state[0]);
  var gameObject1 = match[1];
  var match$1 = MeshRendererTool$Wonderjs.createBasicMaterialGameObject(match[0]);
  var gameObject2 = match$1[1];
  var match$2 = BoxGeometryAPI$Wonderjs.createBoxGeometry(match$1[0]);
  var match$3 = BoxGeometryAPI$Wonderjs.createBoxGeometry(match$2[0]);
  var state$1 = GameObjectAPI$Wonderjs.addGameObjectBoxGeometryComponent(gameObject1, match$2[1], match$3[0]);
  var state$2 = GameObjectAPI$Wonderjs.addGameObjectBoxGeometryComponent(gameObject2, match$3[1], state$1);
  return /* tuple */[
          state$2,
          gameObject1,
          gameObject2
        ];
}

function prepareBoxAndCustomGeometryGameObjects(state) {
  var match = BoxGeometryTool$Wonderjs.createGameObject(state[0]);
  var match$1 = BoxGeometryTool$Wonderjs.createGameObject(match[0]);
  var match$2 = CustomGeometryTool$Wonderjs.createGameObject(match$1[0]);
  return /* tuple */[
          match$2[0],
          /* tuple */[
            match[1],
            match$1[1],
            match$2[1]
          ],
          /* tuple */[
            match[2],
            match$1[2],
            match$2[2]
          ]
        ];
}

exports.prepareForDisposeBoxGeometryVboBuffer = prepareForDisposeBoxGeometryVboBuffer;
exports.prepareForDisposeGameObjects = prepareForDisposeGameObjects;
exports.prepareBoxAndCustomGeometryGameObjects = prepareBoxAndCustomGeometryGameObjects;
/* GameObjectAPI-Wonderjs Not a pure module */
