// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function isChrome(browser) {
  return +(browser === /* Chrome */0);
}

function isFirefox(browser) {
  return +(browser === /* Firefox */1);
}

function isUnknown(browser) {
  return +(browser === /* Unknown */2);
}

export {
  isChrome  ,
  isFirefox ,
  isUnknown ,
  
}
/* No side effect */
