let addFloat32TypeArrayToPool = TypeArrayPoolService.addFloat32TypeArrayToPool;

let addUint16TypeArrayToPool = TypeArrayPoolService.addUint16TypeArrayToPool;

let getFloat32TypeArrayFromPool = TypeArrayPoolService.getFloat32TypeArrayFromPool;

let getFloat32ArrayPoolMap = TypeArrayPoolService.getFloat32ArrayPoolMap;

let getUint16TypeArrayFromPool = TypeArrayPoolService.getUint16TypeArrayFromPool;

let getTypeArrayFromPool = TypeArrayPoolService._getTypeArrayFromPool;