// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE


function getRgb() {
  return 0;
}

function getRgba() {
  return 1;
}

function getAlpha() {
  return 2;
}

function getLuminance() {
  return 3;
}

function getLuminanceAlpha() {
  return 4;
}

function getRgbS3tcDxt1() {
  return 5;
}

function getRgbaS3tcDxt1() {
  return 5;
}

function getRgbaS3tcDxt3() {
  return 5;
}

function getRgbaS3tcDxt5() {
  return 5;
}

function getGlFormat(gl, format) {
  if (format === 0) {
    return gl.RGB;
  } else if (format === 1) {
    return gl.RGBA;
  } else if (format === 2) {
    return gl.ALPHA;
  } else if (format === 3) {
    return gl.LUMINANCE;
  } else if (format === 4) {
    return gl.LUMINANCE_ALPHA;
  } else if (format === 5) {
    return gl.RGB_S3TC_DXT1;
  } else if (format === 5) {
    return gl.RGBA_S3TC_DXT1;
  } else if (format === 5) {
    return gl.RGBA_S3TC_DXT3;
  } else {
    return gl.RGBA_S3TC_DXT5;
  }
}

export {
  getRgb ,
  getRgba ,
  getAlpha ,
  getLuminance ,
  getLuminanceAlpha ,
  getRgbS3tcDxt1 ,
  getRgbaS3tcDxt1 ,
  getRgbaS3tcDxt3 ,
  getRgbaS3tcDxt5 ,
  getGlFormat ,
  
}
/* No side effect */
