// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE


function getRepeat() {
  return 0;
}

function getMirroredRepeat() {
  return 1;
}

function getClampToEdge() {
  return 2;
}

function getGlWrap(gl, wrap) {
  if (wrap === 0) {
    return gl.REAPEAT;
  } else if (wrap === 1) {
    return gl.MIRRORED_REPEAT;
  } else {
    return gl.CLAMP_TO_EDGE;
  }
}

export {
  getRepeat ,
  getMirroredRepeat ,
  getClampToEdge ,
  getGlWrap ,
  
}
/* No side effect */
