// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as CreateLightService$Wonderjs        from "../CreateLightService.js";
import * as MappedIndexService$Wonderjs        from "../../../primitiive/MappedIndexService.js";
import * as RecordAmbientLightService$Wonderjs from "./RecordAmbientLightService.js";

function create(record) {
  var index = record[/* index */0];
  return CreateLightService$Wonderjs.checkNotExceedMaxCount(RecordAmbientLightService$Wonderjs.getBufferMaxCount(/* () */0), /* tuple */[
              /* record */[
                /* index */index + 1 | 0,
                /* buffer */record[/* buffer */1],
                /* colors */record[/* colors */2],
                /* mappedIndexMap */MappedIndexService$Wonderjs.setMappedIndex(index, index, record[/* mappedIndexMap */3]),
                /* gameObjectMap */record[/* gameObjectMap */4]
              ],
              index
            ]);
}

export {
  create ,
  
}
/* CreateLightService-Wonderjs Not a pure module */
