// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE


function getWrapSsSize() {
  return 1;
}

function getWrapTsSize() {
  return 1;
}

function getMagFiltersSize() {
  return 1;
}

function getMinFiltersSize() {
  return 1;
}

function getFormatsSize() {
  return 1;
}

function getTypesSize() {
  return 1;
}

function getIsNeedUpdatesSize() {
  return 1;
}

function getWidthsSize() {
  return 1;
}

function getHeightsSize() {
  return 1;
}

export {
  getWrapSsSize ,
  getWrapTsSize ,
  getMagFiltersSize ,
  getMinFiltersSize ,
  getFormatsSize ,
  getTypesSize ,
  getIsNeedUpdatesSize ,
  getWidthsSize ,
  getHeightsSize ,
  
}
/* No side effect */
