// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as BufferService$Wonderjs                  from "../../../../primitive/buffer/BufferService.js";
import * as BufferSettingService$Wonderjs           from "../../../../record/main/setting/BufferSettingService.js";
import * as IndexComponentService$Wonderjs          from "../../../../primitive/component/IndexComponentService.js";
import * as RecordBasicMaterialMainService$Wonderjs from "./RecordBasicMaterialMainService.js";

function create(state) {
  var basicMaterialRecord = RecordBasicMaterialMainService$Wonderjs.getRecord(state);
  var match = IndexComponentService$Wonderjs.generateIndex(basicMaterialRecord[/* index */0], basicMaterialRecord[/* disposedIndexArray */8]);
  var newrecord = basicMaterialRecord.slice();
  state[/* basicMaterialRecord */15] = /* Some */[(newrecord[/* index */0] = match[1], newrecord)];
  return BufferService$Wonderjs.checkNotExceedMaxCount(BufferSettingService$Wonderjs.getBasicMaterialDataBufferCount(state[/* settingRecord */0]), /* tuple */[
              state,
              match[0]
            ]);
}

export {
  create ,
  
}
/* BufferService-Wonderjs Not a pure module */
