// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as AddComponentService$Wonderjs from "../../../primitive/component/AddComponentService.js";

function handleAddComponent(cameraView, gameObjectUid, record) {
  return /* record */[
          /* index */record[/* index */0],
          /* gameObjectMap */AddComponentService$Wonderjs.addComponentToGameObjectMap(cameraView, gameObjectUid, record[/* gameObjectMap */1]),
          /* disposedIndexArray */record[/* disposedIndexArray */2]
        ];
}

export {
  handleAddComponent ,
  
}
/* No side effect */
