// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function getIsDebug(param) {
  return param[/* isDebug */1];
}

function setIsDebug(isDebug, stateData) {
  stateData[/* isDebug */1] = isDebug;
  return /* () */0;
}

export {
  getIsDebug ,
  setIsDebug ,
  
}
/* No side effect */
