// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as Curry from "../../../../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Sinon from "../../../../../../node_modules/wonder-bs-sinon/lib/es6_global/src/sinon.js";
import * as Caml_array from "../../../../../../node_modules/bs-platform/lib/es6/caml_array.js";
import * as MainStateTool$Wonderjs from "../state/MainStateTool.js";
import * as ParseSettingService$Wonderjs from "../../../../src/service/record/main/setting/ParseSettingService.js";
import * as BufferSettingService$Wonderjs from "../../../../src/service/record/main/setting/BufferSettingService.js";
import * as OperateSettingService$Wonderjs from "../../../../src/service/record/main/setting/OperateSettingService.js";
import * as ConfigDataLoaderSystem$Wonderjs from "../../../../src/asset/ConfigDataLoaderSystem.js";
import * as CreateStateMainService$Wonderjs from "../../../../src/service/state/main/state/CreateStateMainService.js";

function createGetContextStub(fakeGl, sandbox) {
  return Sinon.returns(fakeGl, Curry._1(Sinon.createEmptyStub, sandbox[0]));
}

function buildFakeGl(sandbox) {
  return {
          viewport: Curry._1(Sinon.createEmptyStub, sandbox[0]),
          getParameter: Sinon.returns(0, Curry._1(Sinon.createEmptyStub, sandbox[0])),
          getShaderPrecisionFormat: Sinon.returns({
                precision: 1
              }, Curry._1(Sinon.createEmptyStub, sandbox[0])),
          getExtension: Sinon.returns(1, Curry._1(Sinon.createEmptyStub, sandbox[0]))
        };
}

function buildFakeCanvas(id, gl, sandbox) {
  return {
          id: id,
          nodeType: 1,
          style: {
            left: "",
            top: "",
            width: "",
            height: "",
            position: "static"
          },
          width: 0,
          height: 0,
          getContext: createGetContextStub(gl, sandbox)
        };
}

function buildFakeDomForNotPassCanvasId(sandbox) {
  var fakeGl = buildFakeGl(sandbox);
  var canvasDom = buildFakeCanvas("a", fakeGl, sandbox);
  var div = {
    innerHTML: "",
    firstChild: canvasDom
  };
  var body = {
    prepend: Curry._1(Sinon.createEmptyStub, sandbox[0]),
    style: {
      cssText: ""
    }
  };
  var createElementStub = Curry._3(Sinon.createMethodStub, sandbox[0], document, "createElement");
  Sinon.returns(div, Sinon.withOneArg("div", createElementStub));
  Sinon.returns(canvasDom, Sinon.withOneArg("canvas", createElementStub));
  Sinon.returns(/* :: */[
        body,
        /* [] */0
      ], Sinon.withOneArg("body", Curry._3(Sinon.createMethodStub, sandbox[0], document, "querySelectorAll")));
  return /* tuple */[
          canvasDom,
          fakeGl,
          div,
          body
        ];
}

function buildSetting(isDebug, canvasId, buffer, context, useHardwareInstance, useWorker) {
  if (canvasId) {
    return "\n {\n    \"is_debug\": " + (String(isDebug) + (",\n    \"canvas_id\": \"" + (String(canvasId[0]) + ("\",\n    \"context\": " + (String(context) + (",\n    \"buffer\": " + (String(buffer) + (",\n    \"gpu\": {\n        \"use_hardware_instance\": " + (String(useHardwareInstance) + ("\n    },\n    \"worker\": {\n        \"use_worker\": " + (String(useWorker) + "\n    }\n}\n        ")))))))))));
  } else {
    return "\n {\n    \"is_debug\": " + (String(isDebug) + (",\n    \"context\": " + (String(context) + (",\n    \"buffer\": " + (String(buffer) + (",\n    \"gpu\": {\n        \"use_hardware_instance\": " + (String(useHardwareInstance) + ("\n    },\n    \"worker\": {\n        \"use_worker\": " + (String(useWorker) + "\n    }\n}\n        ")))))))));
  }
}

function buildBufferConfigStr($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, $staropt$star$5, $staropt$star$6, $staropt$star$7, $staropt$star$8, $staropt$star$9, _) {
  var customGeometryPointCount = $staropt$star ? $staropt$star[0] : 300;
  var customGeometryCount = $staropt$star$1 ? $staropt$star$1[0] : 30;
  var transformCount = $staropt$star$2 ? $staropt$star$2[0] : 50;
  var basicMaterialCount = $staropt$star$3 ? $staropt$star$3[0] : 50;
  var lightMaterialCount = $staropt$star$4 ? $staropt$star$4[0] : 50;
  var textureCountPerMaterial = $staropt$star$5 ? $staropt$star$5[0] : 3;
  var basicSourceTextureCount = $staropt$star$6 ? $staropt$star$6[0] : 50;
  var arrayBufferViewSourceTextureCount = $staropt$star$7 ? $staropt$star$7[0] : 50;
  var sourceInstanceCount = $staropt$star$8 ? $staropt$star$8[0] : 2;
  var objectInstanceCountPerSourceInstance = $staropt$star$9 ? $staropt$star$9[0] : 100;
  return "\n       {\n            \"custom_geometry_point_count\": " + (String(customGeometryPointCount) + (",\n            \"custom_geometry_count\": " + (String(customGeometryCount) + (",\n  \"transform_count\": " + (String(transformCount) + (",\n  \"basic_material_count\": " + (String(basicMaterialCount) + (",\n  \"light_material_count\": " + (String(lightMaterialCount) + (",\n  \"basic_source_texture_count\": " + (String(basicSourceTextureCount) + (",\n   \"arrayBuffer_view_source_texture_count\": " + (String(arrayBufferViewSourceTextureCount) + (",\n\n  \"texture_count_per_material\": " + (String(textureCountPerMaterial) + (",\n\n  \"instance_buffer\": {\n    \"sourceInstance_count\": " + (String(sourceInstanceCount) + (",\n\"objectInstance_count_per_source_instance\": " + (String(objectInstanceCountPerSourceInstance) + "\n  }\n       }\n        ")))))))))))))))))));
}

function setToStateData(state, isDebug, canvasId, context, useHardwareInstance, useWorker, buffer) {
  var stateData = MainStateTool$Wonderjs.getStateData(/* () */0);
  return MainStateTool$Wonderjs.setState(ConfigDataLoaderSystem$Wonderjs._createRecordWithState(ConfigDataLoaderSystem$Wonderjs._setSetting(stateData, state, ParseSettingService$Wonderjs.convertToRecord(JSON.parse(buildSetting(isDebug, canvasId, buffer, context, useHardwareInstance, useWorker))))));
}

function createStateAndSetToStateData($staropt$star, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, $staropt$star$5, _) {
  var isDebug = $staropt$star ? $staropt$star[0] : "true";
  var canvasId = $staropt$star$1 ? $staropt$star$1[0] : /* None */0;
  var context = $staropt$star$2 ? $staropt$star$2[0] : "\n        {\n        \"alpha\": true,\n        \"depth\": true,\n        \"stencil\": false,\n        \"antialias\": true,\n        \"premultiplied_alpha\": true,\n        \"preserve_drawing_buffer\": false\n        }\n               ";
  var useHardwareInstance = $staropt$star$3 ? $staropt$star$3[0] : "false";
  var useWorker = $staropt$star$4 ? $staropt$star$4[0] : "false";
  var buffer = $staropt$star$5 ? $staropt$star$5[0] : buildBufferConfigStr(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);
  return setToStateData(CreateStateMainService$Wonderjs.createState(/* () */0), isDebug, canvasId, context, useHardwareInstance, useWorker, buffer);
}

function setMemory(state, $staropt$star, _) {
  var maxDisposeCount = $staropt$star ? $staropt$star[0] : 1000;
  var newrecord = Caml_array.caml_array_dup(state);
  var init = state[/* settingRecord */0];
  var init$1 = OperateSettingService$Wonderjs.unsafeGetMemory(state[/* settingRecord */0]);
  newrecord[/* settingRecord */0] = /* record */[
    /* canvasId */init[/* canvasId */0],
    /* memory : Some */[/* record */[
        /* maxDisposeCount */maxDisposeCount,
        /* maxTypeArrayPoolSize */init$1[/* maxTypeArrayPoolSize */1],
        /* maxBigTypeArrayPoolSize */init$1[/* maxBigTypeArrayPoolSize */2]
      ]],
    /* buffer */init[/* buffer */2],
    /* isDebug */init[/* isDebug */3],
    /* context */init[/* context */4],
    /* gpu */init[/* gpu */5],
    /* worker */init[/* worker */6]
  ];
  return newrecord;
}

function setBufferSize(state, $staropt$star, _) {
  var customGeometryPointCount = $staropt$star ? $staropt$star[0] : 100;
  var newrecord = Caml_array.caml_array_dup(state);
  var init = state[/* settingRecord */0];
  var init$1 = BufferSettingService$Wonderjs.unsafeGetBuffer(state[/* settingRecord */0]);
  newrecord[/* settingRecord */0] = /* record */[
    /* canvasId */init[/* canvasId */0],
    /* memory */init[/* memory */1],
    /* buffer : Some */[/* record */[
        /* customGeometryPointCount */customGeometryPointCount,
        /* customGeometryCount */init$1[/* customGeometryCount */1],
        /* transformCount */init$1[/* transformCount */2],
        /* basicMaterialCount */init$1[/* basicMaterialCount */3],
        /* lightMaterialCount */init$1[/* lightMaterialCount */4],
        /* textureCountPerMaterial */init$1[/* textureCountPerMaterial */5],
        /* basicSourceTextureCount */init$1[/* basicSourceTextureCount */6],
        /* arrayBufferViewSourceTextureCount */init$1[/* arrayBufferViewSourceTextureCount */7],
        /* instanceBuffer */init$1[/* instanceBuffer */8]
      ]],
    /* isDebug */init[/* isDebug */3],
    /* context */init[/* context */4],
    /* gpu */init[/* gpu */5],
    /* worker */init[/* worker */6]
  ];
  return newrecord;
}

function unsafeGetGPU(state) {
  return OperateSettingService$Wonderjs.unsafeGetGPU(state[/* settingRecord */0]);
}

function setGPU(config, state) {
  var newrecord = Caml_array.caml_array_dup(state);
  var init = state[/* settingRecord */0];
  newrecord[/* settingRecord */0] = /* record */[
    /* canvasId */init[/* canvasId */0],
    /* memory */init[/* memory */1],
    /* buffer */init[/* buffer */2],
    /* isDebug */init[/* isDebug */3],
    /* context */init[/* context */4],
    /* gpu : Some */[config],
    /* worker */init[/* worker */6]
  ];
  return newrecord;
}

function setUseWorker(isUseWorker, state) {
  var newrecord = Caml_array.caml_array_dup(state);
  var init = state[/* settingRecord */0];
  newrecord[/* settingRecord */0] = /* record */[
    /* canvasId */init[/* canvasId */0],
    /* memory */init[/* memory */1],
    /* buffer */init[/* buffer */2],
    /* isDebug */init[/* isDebug */3],
    /* context */init[/* context */4],
    /* gpu */init[/* gpu */5],
    /* worker : Some */[/* record */[/* useWorker */isUseWorker]]
  ];
  return newrecord;
}

export {
  createGetContextStub ,
  buildFakeGl ,
  buildFakeCanvas ,
  buildFakeDomForNotPassCanvasId ,
  buildSetting ,
  buildBufferConfigStr ,
  setToStateData ,
  createStateAndSetToStateData ,
  setMemory ,
  setBufferSize ,
  unsafeGetGPU ,
  setGPU ,
  setUseWorker ,
  
}
/* Sinon Not a pure module */
