// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as WorkerService$Wonderjs from "../../../../../../src/service/primitive/worker/WorkerService.js";

var getSelf = WorkerService$Wonderjs.getSelf;

export {
  getSelf ,
  
}
/* WorkerService-Wonderjs Not a pure module */
