// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as GPUStateUtils$Wonderjs from "../../../../../src/renderer/device/gpu/GPUStateUtils.js";

function setPrecision(precision, state) {
  var newrecord = state.slice();
  var init = state[/* gpuDetectData */4];
  newrecord[/* gpuDetectData */4] = /* record */[
    /* extensionInstancedArrays */init[/* extensionInstancedArrays */0],
    /* precision : Some */[precision]
  ];
  return newrecord;
}

var getData = GPUStateUtils$Wonderjs.getGpuDetectData;

export {
  getData      ,
  setPrecision ,
  
}
/* No side effect */
