// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Sinon                                         from "../../../../../../node_modules/wonder-bs-sinon/lib/es6_global/src/sinon.js";
import * as FakeGlTool$Wonderjs                           from "../../gl/FakeGlTool.js";
import * as RenderStateTool$Wonderjs                      from "../../state/RenderStateTool.js";
import * as DeviceManagerService$Wonderjs                 from "../../../../src/service/record/all/device/DeviceManagerService.js";
import * as SparseMapService$WonderCommonlib              from "../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/SparseMapService.js";
import * as ArrayBufferRenderService$Wonderjs             from "../../../../src/service/state/render/vboBuffer/ArrayBufferRenderService.js";
import * as GetVboBufferRenderService$Wonderjs            from "../../../../src/service/state/render/vboBuffer/GetVboBufferRenderService.js";
import * as InstanceBufferRenderService$Wonderjs          from "../../../../src/service/state/render/vboBuffer/InstanceBufferRenderService.js";
import * as ElementArrayBufferRenderService$Wonderjs      from "../../../../src/service/state/render/vboBuffer/ElementArrayBufferRenderService.js";
import * as GetBoxGeometryIndicesRenderService$Wonderjs   from "../../../../src/service/state/render/geometry/box/GetBoxGeometryIndicesRenderService.js";
import * as GetBoxGeometryNormalsRenderService$Wonderjs   from "../../../../src/service/state/render/geometry/box/GetBoxGeometryNormalsRenderService.js";
import * as GetBoxGeometryVerticesRenderService$Wonderjs  from "../../../../src/service/state/render/geometry/box/GetBoxGeometryVerticesRenderService.js";
import * as GetBoxGeometryTexCoordsRenderService$Wonderjs from "../../../../src/service/state/render/geometry/box/GetBoxGeometryTexCoordsRenderService.js";

function getRecord(state) {
  return state[/* vboBufferRecord */34];
}

function getOrCreateBoxGeometryVertexArrayBuffer(geometryIndex, state) {
  var state$1 = RenderStateTool$Wonderjs.createState(state);
  return GetVboBufferRenderService$Wonderjs.getOrCreateBuffer(DeviceManagerService$Wonderjs.unsafeGetGl(state$1[/* deviceManagerRecord */18]), /* tuple */[
              geometryIndex,
              state$1[/* vboBufferRecord */0][/* boxGeometryVertexBufferMap */0]
            ], /* tuple */[
              ArrayBufferRenderService$Wonderjs.createBuffer,
              GetBoxGeometryVerticesRenderService$Wonderjs.getVertices
            ], state$1);
}

function getOrCreateBoxGeometryTexCoordArrayBuffer(geometryIndex, state) {
  var state$1 = RenderStateTool$Wonderjs.createState(state);
  return GetVboBufferRenderService$Wonderjs.getOrCreateBuffer(DeviceManagerService$Wonderjs.unsafeGetGl(state$1[/* deviceManagerRecord */18]), /* tuple */[
              geometryIndex,
              state$1[/* vboBufferRecord */0][/* boxGeometryTexCoordBufferMap */1]
            ], /* tuple */[
              ArrayBufferRenderService$Wonderjs.createBuffer,
              GetBoxGeometryTexCoordsRenderService$Wonderjs.getTexCoords
            ], state$1);
}

function getOrCreateBoxGeometryNormalArrayBuffer(geometryIndex, state) {
  var state$1 = RenderStateTool$Wonderjs.createState(state);
  return GetVboBufferRenderService$Wonderjs.getOrCreateBuffer(DeviceManagerService$Wonderjs.unsafeGetGl(state$1[/* deviceManagerRecord */18]), /* tuple */[
              geometryIndex,
              state$1[/* vboBufferRecord */0][/* boxGeometryNormalBufferMap */2]
            ], /* tuple */[
              ArrayBufferRenderService$Wonderjs.createBuffer,
              GetBoxGeometryNormalsRenderService$Wonderjs.getNormals
            ], state$1);
}

function getOrCreateBoxGeometryElementArrayBuffer(geometryIndex, state) {
  var state$1 = RenderStateTool$Wonderjs.createState(state);
  return GetVboBufferRenderService$Wonderjs.getOrCreateBuffer(DeviceManagerService$Wonderjs.unsafeGetGl(state$1[/* deviceManagerRecord */18]), /* tuple */[
              geometryIndex,
              state$1[/* vboBufferRecord */0][/* boxGeometryElementArrayBufferMap */3]
            ], /* tuple */[
              ElementArrayBufferRenderService$Wonderjs.createBuffer,
              GetBoxGeometryIndicesRenderService$Wonderjs.getIndices
            ], state$1);
}

function getOrCreateInstanceBuffer(sourceInstanceIndex, defaultCapacity, state) {
  var state$1 = RenderStateTool$Wonderjs.createState(state);
  return InstanceBufferRenderService$Wonderjs.getOrCreateBuffer(/* tuple */[
              DeviceManagerService$Wonderjs.unsafeGetGl(state$1[/* deviceManagerRecord */18]),
              sourceInstanceIndex,
              defaultCapacity
            ], /* tuple */[
              state$1[/* sourceInstanceRecord */15][/* matrixInstanceBufferCapacityMap */3],
              state$1[/* vboBufferRecord */0][/* matrixInstanceBufferMap */8]
            ], state$1);
}

function addVboBufferToBoxGeometryBufferMapByRecord(geometryIndex, vboBufferRecord) {
  SparseMapService$WonderCommonlib.set(geometryIndex, 0, vboBufferRecord[/* boxGeometryVertexBufferMap */0]);
  SparseMapService$WonderCommonlib.set(geometryIndex, 1, vboBufferRecord[/* boxGeometryTexCoordBufferMap */1]);
  SparseMapService$WonderCommonlib.set(geometryIndex, 2, vboBufferRecord[/* boxGeometryNormalBufferMap */2]);
  SparseMapService$WonderCommonlib.set(geometryIndex, 3, vboBufferRecord[/* boxGeometryElementArrayBufferMap */3]);
  return vboBufferRecord;
}

function addVboBufferToCustomGeometryBufferMapByRecord(geometryIndex, vboBufferRecord) {
  SparseMapService$WonderCommonlib.set(geometryIndex, 0, vboBufferRecord[/* customGeometryVertexBufferMap */4]);
  SparseMapService$WonderCommonlib.set(geometryIndex, 1, vboBufferRecord[/* customGeometryTexCoordBufferMap */5]);
  SparseMapService$WonderCommonlib.set(geometryIndex, 2, vboBufferRecord[/* customGeometryNormalBufferMap */6]);
  SparseMapService$WonderCommonlib.set(geometryIndex, 3, vboBufferRecord[/* customGeometryElementArrayBufferMap */7]);
  return vboBufferRecord;
}

function addVboBufferToSourceInstanceBufferMapByRecord(sourceInstanceIndex, vboBufferRecord) {
  SparseMapService$WonderCommonlib.set(sourceInstanceIndex, 0, vboBufferRecord[/* matrixInstanceBufferMap */8]);
  return vboBufferRecord;
}

function addVboBufferToBoxGeometryBufferMap(geometryIndex, state) {
  var newrecord = state.slice();
  newrecord[/* vboBufferRecord */34] = addVboBufferToBoxGeometryBufferMapByRecord(geometryIndex, state[/* vboBufferRecord */34]);
  return newrecord;
}

function addVboBufferToCustomGeometryBufferMap(geometryIndex, state) {
  var newrecord = state.slice();
  newrecord[/* vboBufferRecord */34] = addVboBufferToCustomGeometryBufferMapByRecord(geometryIndex, state[/* vboBufferRecord */34]);
  return newrecord;
}

function addVboBufferToSourceInstanceBufferMap(sourceInstanceIndex, state) {
  var newrecord = state.slice();
  newrecord[/* vboBufferRecord */34] = addVboBufferToSourceInstanceBufferMapByRecord(sourceInstanceIndex, state[/* vboBufferRecord */34]);
  return newrecord;
}

function getVboBufferRecord(state) {
  return state[/* vboBufferRecord */34];
}

function prepareCreatedBuffer(sandbox, state) {
  var createBuffer = Sinon.createEmptyStubWithJsObjSandbox(sandbox);
  Sinon.returns(20, Sinon.onCall(0, createBuffer));
  Sinon.returns(21, Sinon.onCall(1, createBuffer));
  Sinon.returns(22, Sinon.onCall(2, createBuffer));
  Sinon.returns(12, Sinon.onCall(3, createBuffer));
  Sinon.returns(22, Sinon.onCall(4, createBuffer));
  Sinon.returns(23, Sinon.onCall(5, createBuffer));
  Sinon.returns(24, Sinon.onCall(6, createBuffer));
  Sinon.returns(13, Sinon.onCall(7, createBuffer));
  var state$1 = FakeGlTool$Wonderjs.setFakeGl(FakeGlTool$Wonderjs.buildFakeGl(sandbox, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[createBuffer], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0), state);
  return /* tuple */[
          state$1,
          /* tuple */[
            20,
            21,
            22,
            23,
            24,
            25
          ],
          /* tuple */[
            12,
            13
          ],
          createBuffer
        ];
}

function getOrCreateAllBoxGeometryBuffers(geometry, state) {
  return /* tuple */[
          getOrCreateBoxGeometryVertexArrayBuffer(geometry, state),
          getOrCreateBoxGeometryTexCoordArrayBuffer(geometry, state),
          getOrCreateBoxGeometryNormalArrayBuffer(geometry, state),
          getOrCreateBoxGeometryElementArrayBuffer(geometry, state)
        ];
}

export {
  getRecord                                     ,
  getOrCreateBoxGeometryVertexArrayBuffer       ,
  getOrCreateBoxGeometryTexCoordArrayBuffer     ,
  getOrCreateBoxGeometryNormalArrayBuffer       ,
  getOrCreateBoxGeometryElementArrayBuffer      ,
  getOrCreateInstanceBuffer                     ,
  addVboBufferToBoxGeometryBufferMapByRecord    ,
  addVboBufferToCustomGeometryBufferMapByRecord ,
  addVboBufferToSourceInstanceBufferMapByRecord ,
  addVboBufferToBoxGeometryBufferMap            ,
  addVboBufferToCustomGeometryBufferMap         ,
  addVboBufferToSourceInstanceBufferMap         ,
  getVboBufferRecord                            ,
  prepareCreatedBuffer                          ,
  getOrCreateAllBoxGeometryBuffers              ,
  
}
/* Sinon Not a pure module */
