// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Curry                     from "../../../../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Caml_array                from "../../../../../../node_modules/bs-platform/lib/es6/caml_array.js";
import * as MostUtils$Wonderjs        from "../../../asset/utils/MostUtils.js";
import * as WorkerService$Wonderjs    from "../../../service/primitiive/worker/WorkerService.js";
import * as JobConfigService$Wonderjs from "../../../service/primitiive/JobConfigService.js";

function execJob(flags, e, _) {
  return MostUtils$Wonderjs.callFunc((function () {
                WorkerService$Wonderjs.postMessage({
                      operateType: Caml_array.caml_array_get(JobConfigService$Wonderjs.unsafeGetFlags(flags), 0)
                    }, Curry._1(WorkerService$Wonderjs.getSelf, /* () */0));
                return e;
              }));
}

export {
  execJob ,
  
}
/* MostUtils-Wonderjs Not a pure module */
