// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as BasicMaterialSystem$Wonderjs from "../../../component/system/material/basic_material/BasicMaterialSystem.js";

var initBasicMaterial = BasicMaterialSystem$Wonderjs.init;

export {
  initBasicMaterial ,
  
}
/* BasicMaterialSystem-Wonderjs Not a pure module */
