// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ArraySystem$Wonderjs         from "../../../../structure/ArraySystem.js";
import * as MaterialAdmin$Wonderjs       from "./MaterialAdmin.js";
import * as LightMaterialSystem$Wonderjs from "../../../component/system/material/light/LightMaterialSystem.js";

function initMaterials(materialIndexArr, gl, state) {
  return ArraySystem$Wonderjs.reduceState((function (state, materialIndex) {
                return LightMaterialSystem$Wonderjs.initMaterial(materialIndex, gl, state);
              }), state, materialIndexArr);
}

var init = LightMaterialSystem$Wonderjs.init;

function restore(gl, currentState, targetState) {
  var newState = LightMaterialSystem$Wonderjs.restore(currentState, targetState);
  return initMaterials(MaterialAdmin$Wonderjs.getAllAliveMaterials(LightMaterialSystem$Wonderjs.getMaterialData(newState)[/* gameObjectMap */5]), gl, newState);
}

var unsafeGetShaderIndex = LightMaterialSystem$Wonderjs.unsafeGetShaderIndex;

var deepCopyStateForRestore = LightMaterialSystem$Wonderjs.deepCopyStateForRestore;

export {
  unsafeGetShaderIndex    ,
  initMaterials           ,
  init                    ,
  deepCopyStateForRestore ,
  restore                 ,
  
}
/* ArraySystem-Wonderjs Not a pure module */
