// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as ArrayService$Wonderjs from "../atom/ArrayService.js";
import * as ArrayService$WonderCommonlib from "../../../../../node_modules/wonder-commonlib/lib/es6_global/src/ArrayService.js";

function create() {
  return ArrayService$WonderCommonlib.createEmpty(/* () */0);
}

var addToDirtyArray = ArrayService$Wonderjs.push;

function getCount(dirtyArray) {
  return dirtyArray.length;
}

export {
  create ,
  addToDirtyArray ,
  getCount ,
  
}
/* ArrayService-Wonderjs Not a pure module */
