// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as MostUtils$Wonderjs                from "../../../../asset/utils/MostUtils.js";
import * as MessageService$Wonderjs           from "../../../../service/primitive/worker/MessageService.js";
import * as StateRenderWorkerService$Wonderjs from "../../../../service/state/render_worker/state/StateRenderWorkerService.js";

function execJob(_, e, stateData) {
  return MostUtils$Wonderjs.callFunc((function () {
                var state = StateRenderWorkerService$Wonderjs.unsafeGetState(stateData);
                var data = MessageService$Wonderjs.getRecord(e);
                var basicMaterialData = data.basicMaterialData;
                state[/* basicMaterialRecord */11] = /* Some */[/* record */[
                    /* buffer */basicMaterialData.buffer,
                    /* shaderIndices : None */0,
                    /* colors : None */0,
                    /* index */basicMaterialData.index,
                    /* disposedIndexArray */basicMaterialData.disposedIndexArray,
                    /* isSourceInstanceMap */basicMaterialData.isSourceInstanceMap
                  ]];
                var lightMaterialData = data.lightMaterialData;
                state[/* lightMaterialRecord */12] = /* Some */[/* record */[
                    /* buffer */lightMaterialData.buffer,
                    /* shaderIndices : None */0,
                    /* diffuseColors : None */0,
                    /* specularColors : None */0,
                    /* shininess : None */0,
                    /* index */lightMaterialData.index,
                    /* disposedIndexArray */lightMaterialData.disposedIndexArray,
                    /* isSourceInstanceMap */lightMaterialData.isSourceInstanceMap
                  ]];
                StateRenderWorkerService$Wonderjs.setState(stateData, state);
                return e;
              }));
}

export {
  execJob ,
  
}
/* MostUtils-Wonderjs Not a pure module */
