// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as SparseMapService$Wonderjs from "../../atom/SparseMapService.js";

var getAllAliveMaterials = SparseMapService$Wonderjs.getValidKeys;

export {
  getAllAliveMaterials ,
  
}
/* SparseMapService-Wonderjs Not a pure module */
