name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: yarn install && lerna bootstrap

    - name: Unit Test
      run: yarn ci:test

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1
    #   with:
    #     token: 300e5f0f-c57a-441b-9266-b552204459a7