// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ArraySystem$WonderCommonlib     from "../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/ArraySystem.js";
import * as SparseMapSystem$WonderCommonlib from "../../../../../../node_modules/wonder-commonlib/lib/es6_global/src/SparseMapSystem.js";

function getIntersectShaderRelatedMap(intersectShaderIndexDataArray, currentMap) {
  return ArraySystem$WonderCommonlib.reduceOneParam((function (intersectMap, param) {
                SparseMapSystem$WonderCommonlib.set(param[1], SparseMapSystem$WonderCommonlib.unsafeGet(param[0], currentMap), intersectMap);
                return intersectMap;
              }), SparseMapSystem$WonderCommonlib.createEmpty(/* () */0), intersectShaderIndexDataArray);
}

export {
  getIntersectShaderRelatedMap ,
  
}
/* ArraySystem-WonderCommonlib Not a pure module */
