// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Json_decode from "../../../../../../../node_modules/bs-json/lib/es6_global/src/Json_decode.js";

function convertSettingToRecord(loop_setting) {
  return /* record */[
          /* initPipeline */Json_decode.field("init_pipeline", Json_decode.string, loop_setting),
          /* loopPipeline */Json_decode.field("loop_pipeline", Json_decode.string, loop_setting)
        ];
}

function _convertPipelinesToRecord(pipelines) {
  return Json_decode.array((function (json) {
                return /* record */[
                        /* name */Json_decode.field("name", Json_decode.string, json),
                        /* jobs */Json_decode.field("jobs", (function (param) {
                                return Json_decode.array((function (json) {
                                              return /* record */[/* name */Json_decode.field("name", Json_decode.string, json)];
                                            }), param);
                              }), json)
                      ];
              }), pipelines);
}

function _convertJobsToRecord(jobs) {
  return Json_decode.array((function (json) {
                return /* record */[
                        /* name */Json_decode.field("name", Json_decode.string, json),
                        /* flags */Json_decode.optional((function (param) {
                                return Json_decode.field("flags", (function (json) {
                                              return Json_decode.array(Json_decode.string, json);
                                            }), param);
                              }), json)
                      ];
              }), jobs);
}

var convertInitPipelinesToRecord = _convertPipelinesToRecord;

var convertInitJobsToRecord = _convertJobsToRecord;

var convertLoopPipelinesToRecord = _convertPipelinesToRecord;

var convertLoopJobsToRecord = _convertJobsToRecord;

export {
  convertSettingToRecord       ,
  _convertPipelinesToRecord    ,
  _convertJobsToRecord         ,
  convertInitPipelinesToRecord ,
  convertInitJobsToRecord      ,
  convertLoopPipelinesToRecord ,
  convertLoopJobsToRecord      ,
  
}
/* No side effect */
